/* eslint-disable */

/**
 * Generated by Verge3D Puzzles v.4.10.0
 * Fri, 04 Jul 2025 12:38:29 GMT
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */
function createPL(v3d = window.v3d) {

// global variables used in the init tab
const _initGlob = {
    percentage: 0,
    output: {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        },
    },
};


// global variables/constants used by puzzles' functions
var _pGlob = {};

_pGlob.objCache = new Map();
_pGlob.fadeAnnotations = true;
_pGlob.pickedObject = '';
_pGlob.hoveredObject = '';
_pGlob.mediaElements = {};
_pGlob.loadedFile = '';
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.openedFile = '';
_pGlob.openedFileMeta = {};
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.intervalTimers = {};
_pGlob.customEvents = new v3d.EventDispatcher();
_pGlob.eventListeners = [];
_pGlob.htmlElements = new Set();
_pGlob.materialsCache = new Map();

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster(); // always check visibility

const createPzLib = ({ v3d=null, appInstance=null }) => {
    function getElement(id, isParent=false) {
        let elem;
        if (Array.isArray(id) && id[0] === 'CONTAINER') {
            if (appInstance !== null) {
                elem = appInstance.container;
            } else if (typeof _initGlob !== 'undefined') {
                // if we are on the initialization stage, we still can have access
                // to the container element
                const contId = _initGlob.container;
                elem = isParent ? parent.document.getElementById(contId)
                        : document.getElementById(contId);
            }
        } else if (Array.isArray(id) && id[0] === 'WINDOW') {
            elem = isParent ? parent : window;
        } else if (Array.isArray(id) && id[0] === 'DOCUMENT') {
            elem = isParent ? parent.document : document;
        } else if (Array.isArray(id) && id[0] === 'BODY') {
            elem = isParent ? parent.document.body : document.body;
        } else if (Array.isArray(id) && id[0] === 'QUERYSELECTOR') {
            elem = isParent ? parent.document.querySelector(id)
                    : document.querySelector(id);
        } else {
            elem = isParent ? parent.document.getElementById(id)
                    : document.getElementById(id);
        }
        return elem;
    }
        
    function getElements(ids, isParent=false) {
        const elems = [];
        if (Array.isArray(ids) && ids[0] !== 'CONTAINER' && ids[0] !== 'WINDOW'
                && ids[0] !== 'DOCUMENT' && ids[0] !== 'BODY'
                && ids[0] !== 'QUERYSELECTOR') {
            for (let i = 0; i < ids.length; i++) {
                elems.push(getElement(ids[i], isParent));
            }
        } else {
            elems.push(getElement(ids, isParent));
        }
        return elems;
    }
        
    function areListenersSame(target0, type0, listener0, optionsOrUseCapture0,
            target1, type1, listener1, optionsOrUseCapture1) {
        const capture0 = Boolean(optionsOrUseCapture0 instanceof Object
                ? optionsOrUseCapture0.capture : optionsOrUseCapture0);
        const capture1 = Boolean(optionsOrUseCapture1 instanceof Object
                ? optionsOrUseCapture1.capture : optionsOrUseCapture1);
        return target0 === target1 && type0 === type1 && listener0 === listener1
                && capture0 === capture1;
    }
        
    function bindListener(target, type, listener, optionsOrUseCapture) {
        const alreadyExists = _pGlob.eventListeners.some(elem => {
            return areListenersSame(elem.target, elem.type, elem.listener,
                    elem.optionsOrUseCapture, target, type, listener,
                    optionsOrUseCapture);
        });
    
        if (!alreadyExists) {
            target.addEventListener(type, listener, optionsOrUseCapture);
            _pGlob.eventListeners.push({ target, type, listener,
                    optionsOrUseCapture });
        }
    }
        
    function isObjectWorthProcessing(obj) {
        return obj.name !== '' &&
                !(obj.isMesh && obj.isMaterialGeneratedMesh) &&
                !obj.isAuxClippingMesh;
    }
        
    function getObjectByName(objName) {
        let objFound = null;
    
        // COMPAT: <4.9.0, old engine, new puzzles
        const isID = v3d.MathUtils.checkUUID ? v3d.MathUtils.checkUUID(objName) : false;
    
        const pGlobAvailable = _pGlob !== undefined;
        if (pGlobAvailable)
            objFound = _pGlob.objCache.get(objName);
    
        if (objFound && (isID ? objFound.uuid === objName : objFound.name === objName))
            return objFound;
    
        function findValidByName(obj, objName) {
            if ((isID ? obj.uuid === objName : obj.name === objName) && isObjectWorthProcessing(obj))
                return obj;
    
            for (let i = 0; i < obj.children.length; i++) {
                const child = obj.children[i];
                const object = findValidByName(child, objName);
                if (object !== null)
                    return object;
            }
    
            return null;
        }
    
        if (appInstance.scene) {
            objFound = findValidByName(appInstance.scene, objName);
            if (objFound && pGlobAvailable)
                _pGlob.objCache.set(objName, objFound);
        }
    
        return objFound;
    }
        
    function getObjectNamesByGroupName(groupName) {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                const objGroupNames = obj.groupNames;
                if (!objGroupNames) {
                    return;
                }
    
                for (let i = 0; i < objGroupNames.length; i++) {
                    const objGroupName = objGroupNames[i];
                    if (objGroupName === groupName) {
                        objNameList.push(obj.name);
                    }
                }
            }
        });
        return objNameList;
    }
        
    function getAllObjectNames() {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                objNameList.push(obj.name);
            }
        });
        return objNameList;
    }
        
    function retrieveObjectNamesAccum(currObjNames, namesAccum) {
        if (typeof currObjNames === 'string') {
            namesAccum.push(currObjNames);
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'GROUP') {
            const newObjNames = getObjectNamesByGroupName(currObjNames[1]);
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'ALL_OBJECTS') {
            const newObjNames = getAllObjectNames();
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames)) {
            for (let i = 0; i < currObjNames.length; i++) {
                retrieveObjectNamesAccum(currObjNames[i], namesAccum);
            }
        }
    }
        
    function retrieveObjectNames(objNames) {
        const accum = [];
        retrieveObjectNamesAccum(objNames, accum);
        return accum.filter(name => name !== '');
    }

    return {
        getElement, getElements, bindListener, getObjectByName,
        retrieveObjectNames,
    };
};

var PL = {};



// backward compatibility
if (v3d[Symbol.toStringTag] !== 'Module') {
    v3d.PL = v3d.puzzles = PL;
}

PL.procedures = PL.procedures || {};




PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;
    // app is more conventional than appInstance (used in exec script and app templates)
    var app = null;

    const PzLib = createPzLib({ v3d });

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    // initSettings puzzle
_initGlob.output.initOptions.fadeAnnotations = true;
_initGlob.output.initOptions.useBkgTransp = false;
_initGlob.output.initOptions.preserveDrawBuf = false;
_initGlob.output.initOptions.useCompAssets = true;
_initGlob.output.initOptions.useFullscreen = true;

    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {

// app is more conventional than appInstance (used in exec script and app templates)
var app = appInstance;

const PzLib = createPzLib({ v3d, appInstance });

initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}



// createCSSRule puzzle
function createCSSRule(cssRule, cssRuleCont, isParent, mediaRule) {
    var style = document.createElement('style');
    style.type = 'text/css';
    if (mediaRule) {
        style.innerHTML = `@media ${mediaRule} { ${cssRule} { ${cssRuleCont} } }`;
    } else {
        style.innerHTML = `${cssRule} { ${cssRuleCont} }`;
    }

    var styles = (isParent) ? parent.document.getElementsByTagName('head')[0] :
                              document.getElementsByTagName('head')[0];
    styles.appendChild(style)
}

// addHTMLElement puzzle
function addHTMLElement(elemType, id, mode, targetId, isParent) {
    const win = isParent ? window.parent : window;

    const elem = win.document.createElement(elemType);
    if (id !== '')
        elem.id = id;

    const targetElem = PzLib.getElement(targetId, isParent);
    if (targetElem instanceof win.Element) {
        switch (mode) {
            case 'TO':
                targetElem.appendChild(elem);
                break;
            case 'BEFORE':
                targetElem.insertAdjacentElement('beforebegin', elem);
                break;
            case 'AFTER':
                targetElem.insertAdjacentElement('afterend', elem);
                break;
        }

        _pGlob.htmlElements.add(elem);
    } else
        console.error('add HTML element puzzle: Invalid element "' + targetId + '"');
}

// setHTMLElemAttribute puzzle
function setHTMLElemAttribute(attr, value, ids, isParent) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem) continue;

        if ((attr == 'href' || attr == 'src') && value instanceof Promise) {
            // resolve promise value for url-based attributes
            value.then(function(response) {
                elem[attr] = response;
            });
        } else {
            elem[attr] = value;
        }
    }
}

// setHTMLElemStyle puzzle
function setHTMLElemStyle(prop, value, ids, isParent) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem || !elem.style)
            continue;
        elem.style[prop] = value;
    }
}

// loadScene puzzle
function loadScene(url, sceneName, loadCb, progCb, errorCb) {

    appInstance.unload();

    // clean object cache
    _pGlob.objCache.clear();

    _pGlob.percentage = 0;
    appInstance.loadScene(url, function(loadedScene) {
        appInstance.enableControls();
        loadedScene.name = sceneName;

        _pGlob.percentage = 100;
        loadCb();
    }, function(percentage) {
        _pGlob.percentage = percentage;
        progCb();
    }, errorCb);
}

// eventHTMLElem puzzle
function eventHTMLElem(eventType, ids, isParent, callback) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem)
            continue;

        PzLib.bindListener(elem, eventType, callback);
    }
}

// setLightParam puzzle
function setLightParam(type, objSelector, param) {

    if (type === 'SHADOW_MAP_FILTERING') {
        const rendererShadowMap = appInstance.renderer.shadowMap;
        if (rendererShadowMap) {
            let shadowMapFilteringTypeBefore = rendererShadowMap.type;

            switch (param) {
                case 'BASIC':
                    rendererShadowMap.type = v3d.BasicShadowMap;
                    break;
                case 'BILINEAR':
                    rendererShadowMap.type = v3d.BilinearShadowMap;
                    break;
                case 'PCF':
                // COMPAT: deprecated, PCF == v3d.PCFShadowMapPoissonDisk since 4.7
                case 'PCFBILINEAR':
                case 'PCFPOISSON':
                    // TODO: PCF == v3d.PCFShadow since 4.8
                    rendererShadowMap.type = v3d.PCFShadowMapPoissonDisk;
                    break;
                case 'ESM':
                    rendererShadowMap.type = v3d.ESMShadowMap;
                    break;
                default:
                    console.error('set light param puzzle: Incompatible shadow map filtering type.')
                    return;
                    break;
            }

            if (shadowMapFilteringTypeBefore != rendererShadowMap.type) {

                let deleteShadowMapFromObj = function(object) {
                    if (!object.shadow) return;

                    if (object.shadow.isDirectionalLightShadowCSM) {
                        object.shadow.updateMaps();

                    } else if (object.shadow) {
                        object.shadow.dispose();
                        // COMPAT: < 4.10
                        if (object.shadow.removeMaps) {
                            object.shadow.removeMaps();
                        } else {
                            object.shadow.map = null;
                            object.shadow._additionalMap2D = null;
                            object.shadow._additionalMapCube = null;
                        }
                    }
                }

                // need to update shadow.map for ESM filtering
                let needToUpdateShadowMaps = shadowMapFilteringTypeBefore == v3d.ESMShadowMap ||
                        rendererShadowMap.type == v3d.ESMShadowMap;
                const compiled = {};
                appInstance.scene.traverse(function(object) {

                    const material = object.material;
                    if (material && object.receiveShadow) {

                        if (Array.isArray(material)) {
                            for (let i = 0; i < material.length; i++) {
                                const material2 = material[i];

                                if (material2.uuid in compiled === false) {
                                    material2.needsUpdate = true;
                                    compiled[material2.uuid] = true;
                                }

                            }

                        } else if (material.uuid in compiled === false) {
                            material.needsUpdate = true;
                            compiled[material.uuid] = true;

                        }
                    }

                    if (needToUpdateShadowMaps)
                        deleteShadowMapFromObj(object);
                });
            }

        }
        return;
    }

    const objNames = PzLib.retrieveObjectNames(objSelector);

    objNames.forEach(function(objName) {
        if (!objName)
            return;

        const obj = PzLib.getObjectByName(objName);
        if (!obj || !obj.isLight)
            return;

        switch (type) {
        case 'COLOR_VECTOR':
            obj.color.r = param[0];
            obj.color.g = param[1];
            obj.color.b = param[2];
            break;
        case 'COLOR_CSS_HEX':
        case 'COLOR_CSS_RGB':
            const color = _pGlob.colorTmp.set(param);
            obj.color.r = color.r;
            obj.color.g = color.g;
            obj.color.b = color.b;
            break;
        case 'INTENSITY':
            if (obj.userData.usePowerUnits)
                obj.power = param;
            else
                obj.intensity = param;
            break;
        case 'USE_SHADOW':
            if (obj.isAmbientLight || obj.isHemisphereLight) {
                console.error('set light param puzzle: Incompatible light source');
                return;
            }
            if (typeof(param) === "boolean")
                obj.castShadow = param;

            break;
        case 'SHADOW_MAP_SIZE':
            if (obj.isAmbientLight || obj.isHemisphereLight) {
                console.error('set light param puzzle: Incompatible light source');
                return;
            }

            if (!obj.shadow) return;

            if (obj.shadow.isDirectionalLightShadowCSM) {
                obj.shadow.mapSize.set(param, param);
                obj.shadow.updateMapSize();

            } else if (obj.shadow) {
                obj.shadow.mapSize.set(param, param);
                obj.shadow.dispose();
                // COMPAT: < 4.10
                if (obj.shadow.removeMaps) {
                    obj.shadow.removeMaps();
                } else {
                    obj.shadow.map = null;
                    obj.shadow._additionalMap2D = null;
                    obj.shadow._additionalMapCube = null;
                }
            }

            break;
        }

    });

}


createCSSRule('.background', ('background-color: black;' + '\n' +
'position: absolute;' + '\n' +
'width: 100%;' + '\n' +
'height: 100%;' + '\n' +
'left: 0;' + '\n' +
'top: 0;' + '\n' +
'z-index: 2;' + '\n' +
'          '), false, '');
addHTMLElement('div', 'background', 'TO', ['CONTAINER'], false);
setHTMLElemAttribute('className', 'background', 'background', false);

createCSSRule('.shadows_menu', ('position: absolute;' + '\n' +
'width: 482px;' + '\n' +
'height: 62px;' + '\n' +
'left: 50%;' + '\n' +
'bottom: 20px;' + '\n' +
'margin-left: -240px;' + '\n' +
'z-index: 1;' + '\n' +
'          '), false, '');
addHTMLElement('div', 'shadows_menu', 'TO', ['CONTAINER'], false);
setHTMLElemAttribute('className', 'shadows_menu', 'shadows_menu', false);

createCSSRule('.menu', ('position: absolute;' + '\n' +
'width: 420px;' + '\n' +
'height: 60px;' + '\n' +
'left: 50%;' + '\n' +
'top: 50%;' + '\n' +
'margin-top: -30px;' + '\n' +
'margin-left: -210px;' + '\n' +
'z-index: 2;' + '\n' +
'          '), false, '');
addHTMLElement('div', 'menu', 'TO', 'background', false);
setHTMLElemAttribute('className', 'menu', 'menu', false);

createCSSRule('.shadows_icon', ('position: static;' + '\n' +
'width: 60px;' + '\n' +
'height: 60px;' + '\n' +
'cursor: pointer;' + '\n' +
'margin-left: 10px;' + '\n' +
'margin-right: 10px;' + '\n' +
'float: left;' + '\n' +
'background-position: top -6px left -6px;' + '\n' +
'border-radius: 12px;' + '\n' +
'font-size:16px;' + '\n' +
'font-weight: bolt;' + '\n' +
'text-align:center;' + '\n' +
'font-family: sans-serif;' + '\n' +
'line-height: 1.3;' + '\n' +
'          '), false, '');

createCSSRule('.light_icon', ('position: static;' + '\n' +
'width: 60px;' + '\n' +
'height: 60px;' + '\n' +
'cursor: pointer;' + '\n' +
'margin-left: 20px;' + '\n' +
'margin-right: 20px;' + '\n' +
'float: left;' + '\n' +
'          '), false, '');

addHTMLElement('div', 'shadows_type_1', 'TO', 'shadows_menu', false);
setHTMLElemAttribute('className', 'shadows_icon', 'shadows_type_1', false);
setHTMLElemStyle('backgroundImage', 'url(\'./icons/shadows_basic.png\')', 'shadows_type_1', false);
setHTMLElemAttribute('innerHTML', 'Basic', 'shadows_type_1', false);

addHTMLElement('div', 'point_icon', 'TO', 'menu', false);
setHTMLElemAttribute('className', 'light_icon', 'point_icon', false);
setHTMLElemStyle('backgroundImage', 'url(\'./icons/point.svg\')', 'point_icon', false);
eventHTMLElem('click', 'point_icon', false, function(event) {
    loadScene('./point.gltf.xz', './point.gltf.xz', function() {
        setHTMLElemStyle('display', 'none', 'background', false);
    }, function() {}, function() {});
});

addHTMLElement('div', 'shadows_type_2', 'TO', 'shadows_menu', false);
setHTMLElemAttribute('className', 'shadows_icon', 'shadows_type_2', false);
setHTMLElemStyle('backgroundImage', 'url(\'./icons/shadows_bilinear.png\')', 'shadows_type_2', false);
setHTMLElemAttribute('innerHTML', 'Bilinear', 'shadows_type_2', false);

addHTMLElement('div', 'shadows_type_3', 'TO', 'shadows_menu', false);
setHTMLElemAttribute('className', 'shadows_icon', 'shadows_type_3', false);
setHTMLElemStyle('backgroundImage', 'url(\'./icons/shadows_pcfpoisson.png\')', 'shadows_type_3', false);
setHTMLElemAttribute('innerHTML', 'PCF', 'shadows_type_3', false);

addHTMLElement('div', 'spot_icon', 'TO', 'menu', false);
setHTMLElemAttribute('className', 'light_icon', 'spot_icon', false);
setHTMLElemStyle('backgroundImage', 'url(\'./icons/spot.svg\')', 'spot_icon', false);
eventHTMLElem('click', 'spot_icon', false, function(event) {
    loadScene('./spot.gltf.xz', './spot.gltf.xz', function() {
        setHTMLElemStyle('display', 'none', 'background', false);
    }, function() {}, function() {});
});

addHTMLElement('div', 'shadows_type_4', 'TO', 'shadows_menu', false);
setHTMLElemAttribute('className', 'shadows_icon', 'shadows_type_4', false);
setHTMLElemStyle('backgroundImage', 'url(\'./icons/shadows_esm.png\')', 'shadows_type_4', false);
setHTMLElemStyle('border', '1px solid red', 'shadows_type_4', false);
setHTMLElemAttribute('innerHTML', 'ESM', 'shadows_type_4', false);

addHTMLElement('div', 'area_icon', 'TO', 'menu', false);
setHTMLElemAttribute('className', 'light_icon', 'area_icon', false);
setHTMLElemStyle('backgroundImage', 'url(\'./icons/area.svg\')', 'area_icon', false);
eventHTMLElem('click', 'area_icon', false, function(event) {
    loadScene('./area.gltf.xz', './area.gltf.xz', function() {
        setHTMLElemStyle('display', 'none', 'background', false);
    }, function() {}, function() {});
});

setLightParam('SHADOW_MAP_SIZE', 'Spot', 256);

eventHTMLElem('click', 'shadows_type_1', false, function(event) {
    setLightParam('SHADOW_MAP_FILTERING', '<none>', 'BASIC');
    setHTMLElemStyle('border', 'none', ['shadows_type_1', 'shadows_type_2', 'shadows_type_3', 'shadows_type_4'], false);
    setHTMLElemStyle('border', '1px solid red', 'shadows_type_1', false);
});
eventHTMLElem('click', 'shadows_type_2', false, function(event) {
    setLightParam('SHADOW_MAP_FILTERING', '<none>', 'BILINEAR');
    setHTMLElemStyle('border', 'none', ['shadows_type_1', 'shadows_type_2', 'shadows_type_3', 'shadows_type_4'], false);
    setHTMLElemStyle('border', '1px solid red', 'shadows_type_2', false);
});
eventHTMLElem('click', 'shadows_type_3', false, function(event) {
    setLightParam('SHADOW_MAP_FILTERING', '<none>', 'PCF');
    setHTMLElemStyle('border', 'none', ['shadows_type_1', 'shadows_type_2', 'shadows_type_3', 'shadows_type_4'], false);
    setHTMLElemStyle('border', '1px solid red', 'shadows_type_3', false);
});
eventHTMLElem('click', 'shadows_type_4', false, function(event) {
    setLightParam('SHADOW_MAP_FILTERING', '<none>', 'ESM');
    setHTMLElemStyle('border', 'none', ['shadows_type_1', 'shadows_type_2', 'shadows_type_3', 'shadows_type_4'], false);
    setHTMLElemStyle('border', '1px solid red', 'shadows_type_4', false);
});

addHTMLElement('div', 'sun_icon', 'TO', 'menu', false);
setHTMLElemAttribute('className', 'light_icon', 'sun_icon', false);
setHTMLElemStyle('backgroundImage', 'url(\'./icons/sun.svg\')', 'sun_icon', false);
eventHTMLElem('click', 'sun_icon', false, function(event) {
    loadScene('./sun.gltf.xz', './sun.gltf.xz', function() {
        setHTMLElemStyle('display', 'none', 'background', false);
    }, function() {}, function() {});
});



} // end of PL.init function

PL.disposeListeners = function() {
    if (_pGlob) {
        _pGlob.eventListeners.forEach(({ target, type, listener, optionsOrUseCapture }) => {
            target.removeEventListener(type, listener, optionsOrUseCapture);
        });
        _pGlob.eventListeners.length = 0;
    }
}

PL.disposeHTMLElements = function() {
    if (_pGlob) {
        _pGlob.htmlElements.forEach(elem => {
            elem.remove();
        });
        _pGlob.htmlElements.clear();
    }
}

PL.disposeMaterialsCache = function() {
    if (_pGlob) {
        for (const mat of _pGlob.materialsCache.values()) {
            mat.dispose();
        }
        _pGlob.materialsCache.clear();
    }
}

PL.dispose = function() {
    PL.disposeListeners();
    PL.disposeHTMLElements();
    PL.disposeMaterialsCache();
    _pGlob = null;
    // backward compatibility
    if (v3d[Symbol.toStringTag] !== 'Module') {
        delete v3d.PL;
        delete v3d.puzzles;
    }
}



return PL;

}

export { createPL };
