/* eslint-disable */

/**
 * Generated by Verge3D Puzzles v.4.10.0
 * Fri, 04 Jul 2025 12:36:56 GMT
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */
function createPL(v3d = window.v3d) {

// global variables used in the init tab
const _initGlob = {
    percentage: 0,
    output: {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        },
    },
};


// global variables/constants used by puzzles' functions
var _pGlob = {};

_pGlob.objCache = new Map();
_pGlob.fadeAnnotations = true;
_pGlob.pickedObject = '';
_pGlob.hoveredObject = '';
_pGlob.mediaElements = {};
_pGlob.loadedFile = '';
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.openedFile = '';
_pGlob.openedFileMeta = {};
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.intervalTimers = {};
_pGlob.customEvents = new v3d.EventDispatcher();
_pGlob.eventListeners = [];
_pGlob.htmlElements = new Set();
_pGlob.materialsCache = new Map();

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster(); // always check visibility

const createPzLib = ({ v3d=null, appInstance=null }) => {
    function getElement(id, isParent=false) {
        let elem;
        if (Array.isArray(id) && id[0] === 'CONTAINER') {
            if (appInstance !== null) {
                elem = appInstance.container;
            } else if (typeof _initGlob !== 'undefined') {
                // if we are on the initialization stage, we still can have access
                // to the container element
                const contId = _initGlob.container;
                elem = isParent ? parent.document.getElementById(contId)
                        : document.getElementById(contId);
            }
        } else if (Array.isArray(id) && id[0] === 'WINDOW') {
            elem = isParent ? parent : window;
        } else if (Array.isArray(id) && id[0] === 'DOCUMENT') {
            elem = isParent ? parent.document : document;
        } else if (Array.isArray(id) && id[0] === 'BODY') {
            elem = isParent ? parent.document.body : document.body;
        } else if (Array.isArray(id) && id[0] === 'QUERYSELECTOR') {
            elem = isParent ? parent.document.querySelector(id)
                    : document.querySelector(id);
        } else {
            elem = isParent ? parent.document.getElementById(id)
                    : document.getElementById(id);
        }
        return elem;
    }
        
    function getElements(ids, isParent=false) {
        const elems = [];
        if (Array.isArray(ids) && ids[0] !== 'CONTAINER' && ids[0] !== 'WINDOW'
                && ids[0] !== 'DOCUMENT' && ids[0] !== 'BODY'
                && ids[0] !== 'QUERYSELECTOR') {
            for (let i = 0; i < ids.length; i++) {
                elems.push(getElement(ids[i], isParent));
            }
        } else {
            elems.push(getElement(ids, isParent));
        }
        return elems;
    }
        
    function areListenersSame(target0, type0, listener0, optionsOrUseCapture0,
            target1, type1, listener1, optionsOrUseCapture1) {
        const capture0 = Boolean(optionsOrUseCapture0 instanceof Object
                ? optionsOrUseCapture0.capture : optionsOrUseCapture0);
        const capture1 = Boolean(optionsOrUseCapture1 instanceof Object
                ? optionsOrUseCapture1.capture : optionsOrUseCapture1);
        return target0 === target1 && type0 === type1 && listener0 === listener1
                && capture0 === capture1;
    }
        
    function bindListener(target, type, listener, optionsOrUseCapture) {
        const alreadyExists = _pGlob.eventListeners.some(elem => {
            return areListenersSame(elem.target, elem.type, elem.listener,
                    elem.optionsOrUseCapture, target, type, listener,
                    optionsOrUseCapture);
        });
    
        if (!alreadyExists) {
            target.addEventListener(type, listener, optionsOrUseCapture);
            _pGlob.eventListeners.push({ target, type, listener,
                    optionsOrUseCapture });
        }
    }
        
    function getSceneAnimFrameRate(scene) {
        if (scene && 'animFrameRate' in scene.userData) {
            return scene.userData.animFrameRate;
        }
        return 24;
    }
        
    function getSceneByAction(action) {
        const root = action.getRoot();
        let scene = root.type === 'Scene' ? root : null;
        root.traverseAncestors(ancObj => {
            if (ancObj.type === 'Scene') {
                scene = ancObj;
            }
        });
        return scene;
    }
        
    function transformCoordsSpace(coords, spaceFrom, spaceTo, noSignChange=false) {
    
        if (spaceFrom === spaceTo) {
            return coords;
        }
    
        const y = coords.y;
        const z = coords.z;
    
        if (spaceFrom === 'Z_UP_RIGHT' && spaceTo === 'Y_UP_RIGHT') {
            coords.y = z;
            coords.z = noSignChange ? y : -y;
        } else if (spaceFrom === 'Y_UP_RIGHT' && spaceTo === 'Z_UP_RIGHT') {
            coords.y = noSignChange ? z : -z;
            coords.z = y;
        } else {
            console.error('transformCoordsSpace: Unsupported coordinate space');
        }
    
        return coords;
    }
        
    const transformEulerV3dToBlenderShortest = function() {
        const eulerTmp = new v3d.Euler();
        const eulerTmp2 = new v3d.Euler();
        const vec3Tmp = new v3d.Vector3();
    
        return function(euler, dest) {
            const eulerBlender = eulerTmp.copy(euler).reorder('YZX');
            const eulerBlenderAlt = eulerTmp2.copy(eulerBlender).makeAlternative();
    
            const len = vec3Tmp.setFromEuler(eulerBlender).lengthSq();
            const lenAlt = vec3Tmp.setFromEuler(eulerBlenderAlt).lengthSq();
    
            dest.copy(len < lenAlt ? eulerBlender : eulerBlenderAlt);
            return transformCoordsSpace(dest, 'Y_UP_RIGHT', 'Z_UP_RIGHT');
        }
    }();
        
    function getSceneCoordSystem() {
        const scene = appInstance.scene;
        if (scene && 'coordSystem' in scene.userData) {
            return scene.userData.coordSystem;
        }
    
        return 'Y_UP_RIGHT';
    }
        
    function isObjectWorthProcessing(obj) {
        return obj.name !== '' &&
                !(obj.isMesh && obj.isMaterialGeneratedMesh) &&
                !obj.isAuxClippingMesh;
    }
        
    function getObjectByName(objName) {
        let objFound = null;
    
        // COMPAT: <4.9.0, old engine, new puzzles
        const isID = v3d.MathUtils.checkUUID ? v3d.MathUtils.checkUUID(objName) : false;
    
        const pGlobAvailable = _pGlob !== undefined;
        if (pGlobAvailable)
            objFound = _pGlob.objCache.get(objName);
    
        if (objFound && (isID ? objFound.uuid === objName : objFound.name === objName))
            return objFound;
    
        function findValidByName(obj, objName) {
            if ((isID ? obj.uuid === objName : obj.name === objName) && isObjectWorthProcessing(obj))
                return obj;
    
            for (let i = 0; i < obj.children.length; i++) {
                const child = obj.children[i];
                const object = findValidByName(child, objName);
                if (object !== null)
                    return object;
            }
    
            return null;
        }
    
        if (appInstance.scene) {
            objFound = findValidByName(appInstance.scene, objName);
            if (objFound && pGlobAvailable)
                _pGlob.objCache.set(objName, objFound);
        }
    
        return objFound;
    }
        
    function getObjectNamesByGroupName(groupName) {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                const objGroupNames = obj.groupNames;
                if (!objGroupNames) {
                    return;
                }
    
                for (let i = 0; i < objGroupNames.length; i++) {
                    const objGroupName = objGroupNames[i];
                    if (objGroupName === groupName) {
                        objNameList.push(obj.name);
                    }
                }
            }
        });
        return objNameList;
    }
        
    function getAllObjectNames() {
        const objNameList = [];
        appInstance.scene.traverse(obj => {
            if (isObjectWorthProcessing(obj)) {
                objNameList.push(obj.name);
            }
        });
        return objNameList;
    }
        
    function retrieveObjectNamesAccum(currObjNames, namesAccum) {
        if (typeof currObjNames === 'string') {
            namesAccum.push(currObjNames);
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'GROUP') {
            const newObjNames = getObjectNamesByGroupName(currObjNames[1]);
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames) && currObjNames[0] === 'ALL_OBJECTS') {
            const newObjNames = getAllObjectNames();
            for (let i = 0; i < newObjNames.length; i++) {
                namesAccum.push(newObjNames[i]);
            }
        } else if (Array.isArray(currObjNames)) {
            for (let i = 0; i < currObjNames.length; i++) {
                retrieveObjectNamesAccum(currObjNames[i], namesAccum);
            }
        }
    }
        
    function retrieveObjectNames(objNames) {
        const accum = [];
        retrieveObjectNamesAccum(objNames, accum);
        return accum.filter(name => name !== '');
    }
        
    function RotationInterface() {
        /**
         * @ignore
         * For user manipulations use XYZ extrinsic rotations (which
         * are the same as ZYX intrinsic rotations)
         *     - Blender/Max/Maya use extrinsic rotations in the UI
         *     - XYZ is the default option, but could be set from
         *       some order hint if exported
         */
        this._userRotation = new v3d.Euler(0, 0, 0, 'ZYX');
        this._actualRotation = new v3d.Euler();
    }
    
    Object.assign(RotationInterface, {
        initObject: function(obj) {
            if (obj.userData.puzzles === undefined) {
                obj.userData.puzzles = {}
            }
            if (obj.userData.puzzles.rotationInterface === undefined) {
                obj.userData.puzzles.rotationInterface = new RotationInterface();
            }
    
            const rotUI = obj.userData.puzzles.rotationInterface;
            rotUI.updateFromObject(obj);
            return rotUI;
        },
    });
    
    Object.assign(RotationInterface.prototype, {
        updateFromObject: function(obj) {
            const SYNC_ROT_EPS = 1e-8;
    
            if (!this._actualRotation.equalsEps(obj.rotation, SYNC_ROT_EPS)) {
                this._actualRotation.copy(obj.rotation);
                this._updateUserRotFromActualRot();
            }
        },
    
        getActualRotation: function(euler) {
            return euler.copy(this._actualRotation);
        },
    
        setUserRotation: function(euler) {
            // don't copy the order, since it's fixed to ZYX for now
            this._userRotation.set(euler.x, euler.y, euler.z);
            this._updateActualRotFromUserRot();
        },
    
        getUserRotation: function(euler) {
            return euler.copy(this._userRotation);
        },
    
        _updateUserRotFromActualRot: function() {
            const order = this._userRotation.order;
            this._userRotation.copy(this._actualRotation).reorder(order);
        },
    
        _updateActualRotFromUserRot: function() {
            const order = this._actualRotation.order;
            this._actualRotation.copy(this._userRotation).reorder(order);
        },
    });
        
    class MediaHTML5 {
        constructor() {
            this.source = null;
        }
    
        load(url, isVideo) {
            if (isVideo) {
                this.source = document.createElement('video');
                this.source.playsInline = true;
                this.source.preload = 'auto';
                this.source.autoload = true;
                this.source.crossOrigin = 'anonymous';
            } else {
                this.source = document.createElement('audio');
            }
    
            this.source.src = url;
            return this;
        }
    
        play() {
            this.source.play();
        }
    
        pause() {
            this.source.pause();
        }
    
        stop() {
            this.source.pause();
            this.source.currentTime = 0;
        }
    
        rewind() {
            this.source.currentTime = 0;
        }
    
        setPlaybackTime(time) {
            this.source.currentTime = time
        }
    
        getPlaybackTime() {
            return this.source.currentTime;
        }
    
        getDuration() {
            return this.source.duration;
        }
    
        setPlaybackRate(rate) {
            this.source.playbackRate = rate;
        }
    
        isPlaying() {
            return this.source.duration > 0 && !this.source.paused;
        }
    
        setLoop(looped) {
            this.source.loop = looped;
        }
    
        setVolume(volume) {
            this.source.volume = volume;
        }
    
        setMuted(muted) {
            this.source.muted = muted;
        }
    
        toPositional() {
            if (!(this.audio instanceof v3d.PositionalAudio)) {
                const posAudio = new v3d.PositionalAudio(new v3d.AudioListener());
                posAudio.setMediaElementSource(this.source);
                this.audio = posAudio;
            }
            return this.audio;
        }
    }
        
    class AudioWebAudio {
        constructor() {
            this.audio = new v3d.Audio(new v3d.AudioListener());
    
            this._muted = false;
            this._volume = 1;
        }
    
        load(url) {
            const scope = this;
    
            const xhr = new XMLHttpRequest();
            xhr.open('GET', url);
            xhr.responseType = 'arraybuffer';
    
            xhr.onload = function(e) {
                if (this.status === 200) {
                    // new promise-based syntax is not currently supported in Safari
                    scope.audio.context.decodeAudioData(this.response, function(decodedData) {
                        scope.audio.setBuffer(decodedData);
                    });
                }
            }
    
            xhr.send();
            return this;
        }
    
        play() {
            if (this.audio.buffer === null) return;
            this.audio.play();
        }
    
        pause() {
            this.audio.pause();
        }
    
        stop() {
            if (this.audio.buffer === null || this.audio.source === null) return;
            this.audio.stop();
        }
    
        rewind() {
            if (this.audio.buffer === null || this.audio.source === null) return;
    
            const isPlaying = this.audio.isPlaying;
            this.audio.stop();
            if (isPlaying) {
                this.audio.play();
            }
        }
    
        setPlaybackTime(time) {
            // TODO: not easy with WebAudio
        }
    
        getPlaybackTime() {
            // TODO: not easy with WebAudio
            return 0;
        }
    
        getDuration() {
            return (this.audio.buffer === null) ? 0 : this.audio.buffer.duration;
        }
    
        setPlaybackRate(rate) {
            this.audio.setPlaybackRate(rate);
        }
    
        isPlaying() {
            return this.audio.isPlaying;
        }
    
        setLoop(looped) {
            this.audio.setLoop(looped);
        }
    
        setVolume(volume) {
            this._volume = volume;
            if (!this._muted) {
                this.audio.setVolume(volume);
            }
        }
    
        setMuted(muted) {
            this._muted = muted;
            this.audio.setVolume(muted ? 0 : this._volume);
        }
    
        toPositional() {
            if (!(this.audio instanceof v3d.PositionalAudio)) {
                const posAudio = new v3d.PositionalAudio(this.audio.listener);
                posAudio.fromAudio(this.audio);
                this.audio = posAudio;
            }
            return this.audio;
        }
    }
        
    function removeObject(obj, objName) {
        if (obj.isClippingPlaneObject)
            // COMPAT: < 4.10, new puzzles, old engine
            if (v3d.SceneUtils.removeClipPlanesFromMats)
                v3d.SceneUtils.removeClipPlanesFromMats(obj, appInstance.scene);
    
        obj.parent.remove(obj);
    
        // remove object and its children from cache
        _pGlob.objCache.delete(objName);
    
        obj.traverse(child => {
            _pGlob.objCache.delete(child.name);
        });
    }
        
    function generateUniqueName(name, isUniqueCb) {
        let uniqueName = name;
    
        if (isUniqueCb !== undefined) {
            while (!isUniqueCb(uniqueName)) {
                const r = uniqueName.match(/^(.*?)(\d+)$/);
                if (!r) {
                    uniqueName += '2';
                } else {
                    uniqueName = r[1] + (Number.parseInt(r[2], 10) + 1);
                }
            }
        }
    
        return uniqueName;
    }
        
    function generateUniqueObjectName(name) {
        return generateUniqueName(name, name => !Boolean(getObjectByName(name)));
    }
        
    const LIST_NONE = '<none>';

    return {
        getElement, getElements, bindListener, getSceneAnimFrameRate,
        getSceneByAction, transformCoordsSpace, transformEulerV3dToBlenderShortest, getSceneCoordSystem,
        getObjectByName, retrieveObjectNames, RotationInterface, MediaHTML5,
        AudioWebAudio, removeObject, generateUniqueObjectName, LIST_NONE,
    };
};

var PL = {};



// backward compatibility
if (v3d[Symbol.toStringTag] !== 'Module') {
    v3d.PL = v3d.puzzles = PL;
}

PL.procedures = PL.procedures || {};




PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;
    // app is more conventional than appInstance (used in exec script and app templates)
    var app = null;

    const PzLib = createPzLib({ v3d });

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    var color;

// loadFont puzzle
function loadFont(url, family) {

    if (!url || !family)
        return;

    // register in CSS
    var elemStyle = document.createElement('style');
    elemStyle.innerHTML = '@font-face { font-family: ' + family
        + '; src: url(' + url + '); }';
    document.body.appendChild(elemStyle);

    // preload font
    var elemDiv = document.createElement('div');
    elemDiv.innerHTML = 'invisible text';
    elemDiv.style.visibility = 'hidden';
    elemDiv.style.fontFamily = family;
    document.body.appendChild(elemDiv);
}

// addHTMLElement puzzle
function addHTMLElement(elemType, id, mode, targetId, isParent) {
    const win = isParent ? window.parent : window;

    const elem = win.document.createElement(elemType);
    if (id !== '')
        elem.id = id;

    const targetElem = PzLib.getElement(targetId, isParent);
    if (targetElem instanceof win.Element) {
        switch (mode) {
            case 'TO':
                targetElem.appendChild(elem);
                break;
            case 'BEFORE':
                targetElem.insertAdjacentElement('beforebegin', elem);
                break;
            case 'AFTER':
                targetElem.insertAdjacentElement('afterend', elem);
                break;
        }

        _pGlob.htmlElements.add(elem);
    } else
        console.error('add HTML element puzzle: Invalid element "' + targetId + '"');
}

// setHTMLElemAttribute puzzle
function setHTMLElemAttribute(attr, value, ids, isParent) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem) continue;

        if ((attr == 'href' || attr == 'src') && value instanceof Promise) {
            // resolve promise value for url-based attributes
            value.then(function(response) {
                elem[attr] = response;
            });
        } else {
            elem[attr] = value;
        }
    }
}

// setHTMLElemStyle puzzle
function setHTMLElemStyle(prop, value, ids, isParent) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem || !elem.style)
            continue;
        elem.style[prop] = value;
    }
}

// setTimeout puzzle
function registerSetTimeout(timeout, callback) {
    window.setTimeout(callback, 1000 * timeout);
}



// initSettings puzzle
_initGlob.output.initOptions.fadeAnnotations = true;
_initGlob.output.initOptions.useBkgTransp = false;
_initGlob.output.initOptions.preserveDrawBuf = false;
_initGlob.output.initOptions.useCompAssets = true;
_initGlob.output.initOptions.useFullscreen = false;

loadFont('media/ChangaOne.ttf', 'ChangaOne');

/* Preloader Bar */

addHTMLElement('div', 'preloader_locker', 'TO', ['CONTAINER'], false);
setHTMLElemAttribute('style', "position: absolute; width: 100%; height: 100%; z-index: 14; background-color: #d0e2ff;", 'preloader_locker', false);

addHTMLElement('div', 'preloader_bar_container', 'TO', 'preloader_locker', false);
setHTMLElemAttribute('style', "position: absolute; width: 128px; height: 174px; top: 50%; margin-top: -87px; left: 50%; margin-left: -64px;", 'preloader_bar_container', false);

addHTMLElement('div', 'preloader_bar_apple_green', 'TO', 'preloader_bar_container', false);
setHTMLElemAttribute('style', "position: absolute; width: 128px; height: 128px; top: 0px; background-image: url(\'media/apple_green.gif\');", 'preloader_bar_apple_green', false);

addHTMLElement('div', 'preloader_bar_apple_red', 'TO', 'preloader_bar_apple_green', false);
setHTMLElemAttribute('style', "position: absolute; width: 128px; height: 0%; bottom: 0px; background-image: url(\'media/apple_red.gif\'); background-size: 128px 128px; background-position: bottom; background-repeat: no-repeat;", 'preloader_bar_apple_red', false);

addHTMLElement('div', 'preloader_bar_loading_percentage', 'TO', 'preloader_bar_container', false);
setHTMLElemAttribute('style', "position: absolute; width: 100%; height: 30px; bottom: 0px; font-family: ChangaOne; font-size: 26px; text-align: center;", 'preloader_bar_loading_percentage', false);


// initPreloader puzzle
_initGlob.output.initOptions.useCustomPreloader = true;
_initGlob.output.initOptions.preloaderStartCb = function() {
    _initGlob.percentage = 0;
    (function() {})();
};
_initGlob.output.initOptions.preloaderProgressCb = function(percentage) {
    _initGlob.percentage = percentage;
    (function() {
    color = ['rgba(',61 + (194 / 100) * Math.round(_initGlob.percentage),', ',219 - (219 / 100) * Math.round(_initGlob.percentage),', 0, 1)'].join('');
    setHTMLElemAttribute('innerHTML', String(Math.round(_initGlob.percentage)) + '%', 'preloader_bar_loading_percentage', true);
    setHTMLElemStyle('height', String(Math.round(_initGlob.percentage)) + '%', 'preloader_bar_apple_red', true);
    setHTMLElemStyle('color', color, 'preloader_bar_loading_percentage', true);
})();
};
_initGlob.output.initOptions.preloaderEndCb = function() {
    _initGlob.percentage = 100;
    (function() {
    registerSetTimeout(0.1, function() {
        setHTMLElemStyle('display', 'none', 'preloader_locker', true);
    });
})();
};

    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {

// app is more conventional than appInstance (used in exec script and app templates)
var app = appInstance;

const PzLib = createPzLib({ v3d, appInstance });

initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}

this.procedures["Randomize_Empty"] = Randomize_Empty;
this.procedures["Move_Left"] = Move_Left;
this.procedures["Move_Right"] = Move_Right;
this.procedures["score_time_counting"] = score_time_counting;
this.procedures["fruits_counting"] = fruits_counting;
this.procedures["start_game"] = start_game;

var media_common, add_time, add_score, index, media_portrait, media_width_max600px, media_height_max600px, emptys_with_fruits, random_numder, j, scores, e, emptys_distance, ground_speed, fruits_max, time, game_started, farmer_posotion_next, empty_to_check, i, empty_index, move_steps, help_mode, fruits_amount, gamepad_timestamp, fruit_count, farmers_position, random_empty, ground_speed_temp, farmer_position_prev, fruit_clone, m;

// addHTMLElement puzzle
function addHTMLElement(elemType, id, mode, targetId, isParent) {
    const win = isParent ? window.parent : window;

    const elem = win.document.createElement(elemType);
    if (id !== '')
        elem.id = id;

    const targetElem = PzLib.getElement(targetId, isParent);
    if (targetElem instanceof win.Element) {
        switch (mode) {
            case 'TO':
                targetElem.appendChild(elem);
                break;
            case 'BEFORE':
                targetElem.insertAdjacentElement('beforebegin', elem);
                break;
            case 'AFTER':
                targetElem.insertAdjacentElement('afterend', elem);
                break;
        }

        _pGlob.htmlElements.add(elem);
    } else
        console.error('add HTML element puzzle: Invalid element "' + targetId + '"');
}

// setHTMLElemAttribute puzzle
function setHTMLElemAttribute(attr, value, ids, isParent) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem) continue;

        if ((attr == 'href' || attr == 'src') && value instanceof Promise) {
            // resolve promise value for url-based attributes
            value.then(function(response) {
                elem[attr] = response;
            });
        } else {
            elem[attr] = value;
        }
    }
}

// createCSSRule puzzle
function createCSSRule(cssRule, cssRuleCont, isParent, mediaRule) {
    var style = document.createElement('style');
    style.type = 'text/css';
    if (mediaRule) {
        style.innerHTML = `@media ${mediaRule} { ${cssRule} { ${cssRuleCont} } }`;
    } else {
        style.innerHTML = `${cssRule} { ${cssRuleCont} }`;
    }

    var styles = (isParent) ? parent.document.getElementsByTagName('head')[0] :
                              document.getElementsByTagName('head')[0];
    styles.appendChild(style)
}

// setHTMLElemStyle puzzle
function setHTMLElemStyle(prop, value, ids, isParent) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem || !elem.style)
            continue;
        elem.style[prop] = value;
    }
}

_pGlob.animMixerCallbacks = [];

const initAnimationMixer = function() {

    function onMixerFinished(e) {
        const cb = _pGlob.animMixerCallbacks;
        const found = [];
        for (let i = 0; i < cb.length; i++) {
            if (cb[i][0] == e.action) {
                cb[i][0] = null; // desactivate
                found.push(cb[i][1]);
            }
        }
        for (let i = 0; i < found.length; i++) {
            found[i]();
        }
    }

    return function initAnimationMixer() {
        if (appInstance.mixer && !appInstance.mixer.hasEventListener('finished', onMixerFinished)) {
            PzLib.bindListener(appInstance.mixer, 'finished', onMixerFinished);
        }
    };

}();

// animation puzzles
function operateAnimation(operation, animations, from, to, loop, speed, callback, rev) {
    if (!animations)
        return;
    // input can be either single obj or array of objects
    if (typeof animations == "string")
        animations = [animations];

    function processAnimation(animName) {
        const action = v3d.SceneUtils.getAnimationActionByName(appInstance, animName);
        if (!action)
            return;

        let scene, frameRate, timeScale, callbacks;

        switch (operation) {
        case 'PLAY':
            if (!action.isRunning()) {
                action.reset();

                if (loop == 'AUTO') {
                    // COMPAT: < 4.10, old engine, new puzzles (no autoParams)
                    if (action.autoParams) {
                        action.loop = action.autoParams.loop;
                        action.repetitions = action.autoParams.repetitions;
                    } else {
                        action.repetitions = Infinity;
                    }
                } else {
                    action.loop = v3d[loop];
                    action.repetitions = Infinity;
                }

                scene = PzLib.getSceneByAction(action);
                frameRate = PzLib.getSceneAnimFrameRate(scene);
                timeScale = Math.abs(parseFloat(speed));

                if (rev)
                    timeScale *= -1;

                action.timeScale = timeScale;
                action.timeStart = from !== null ? from/frameRate : 0;
                if (to !== null) {
                    action.getClip().duration = to/frameRate;
                } else {
                    action.getClip().resetDuration();
                }
                action.time = timeScale >= 0 ? action.timeStart : action.getClip().duration;

                action.paused = false;
                action.play();

                // push unique callbacks only
                callbacks = _pGlob.animMixerCallbacks;
                let found = false;
                for (let j = 0; j < callbacks.length; j++)
                    if (callbacks[j][0] == action && callbacks[j][1] == callback)
                        found = true;

                if (!found)
                    _pGlob.animMixerCallbacks.push([action, callback]);
            }
            break;
        case 'STOP':
            action.stop();

            // remove callbacks
            callbacks = _pGlob.animMixerCallbacks;
            for (let j = 0; j < callbacks.length; j++)
                if (callbacks[j][0] == action) {
                    callbacks.splice(j, 1);
                    j--;
                }

            break;
        case 'PAUSE':
            action.paused = true;
            break;
        case 'RESUME':
            action.paused = false;
            break;
        case 'SET_FRAME':
            scene = PzLib.getSceneByAction(action);
            frameRate = PzLib.getSceneAnimFrameRate(scene);
            action.time = from ? from/frameRate : 0;
            action.play();
            action.paused = true;
            break;
        case 'SET_SPEED':
            timeScale = parseFloat(speed);
            action.timeScale = rev ? -timeScale : timeScale;
            break;
        }
    }

    for (let i = 0; i < animations.length; i++) {
        const animName = animations[i];
        if (animName)
            processAnimation(animName);
    }

    initAnimationMixer();
}

// setObjTransform puzzle
function setObjTransform(objSelector, isWorldSpace, mode, vector, offset) {
    const x = vector[0];
    const y = vector[1];
    const z = vector[2];

    if (isNaN(x) || isNaN(y) || isNaN(z)) {
        console.error('set transform puzzle: Invalid transform');
        return;
    }

    const objNames = PzLib.retrieveObjectNames(objSelector);

    function setObjProp(obj, prop, val) {
        if (!offset) {
            obj[mode][prop] = val;
        } else {
            if (mode != "scale")
                obj[mode][prop] += val;
            else
                obj[mode][prop] *= val;
        }
    }

    const inputsUsed = _pGlob.vec3Tmp.set(Number(x !== ''), Number(y !== ''), Number(z !== ''));
    const coords = _pGlob.vec3Tmp2.set(x || 0, y || 0, z || 0);

    if (mode === 'rotation') {
        // rotations are specified in degrees
        coords.multiplyScalar(v3d.MathUtils.DEG2RAD);
    }

    const coordSystem = PzLib.getSceneCoordSystem();

    PzLib.transformCoordsSpace(inputsUsed, coordSystem, 'Y_UP_RIGHT', true);
    PzLib.transformCoordsSpace(coords, coordSystem, 'Y_UP_RIGHT', mode === 'scale');

    for (let i = 0; i < objNames.length; i++) {

        const objName = objNames[i];
        if (!objName) continue;

        const obj = PzLib.getObjectByName(objName);
        if (!obj) continue;

        if (isWorldSpace && obj.parent) {
            obj.matrixWorld.decomposeE(obj.position, obj.rotation, obj.scale);

            if (inputsUsed.x) setObjProp(obj, "x", coords.x);
            if (inputsUsed.y) setObjProp(obj, "y", coords.y);
            if (inputsUsed.z) setObjProp(obj, "z", coords.z);

            obj.matrixWorld.composeE(obj.position, obj.rotation, obj.scale);
            obj.matrix.multiplyMatrices(_pGlob.mat4Tmp.copy(obj.parent.matrixWorld).invert(), obj.matrixWorld);
            obj.matrix.decompose(obj.position, obj.quaternion, obj.scale);

        } else if (mode === 'rotation' && coordSystem == 'Z_UP_RIGHT') {
            // Blender/Max coordinates

            // need all the rotations for order conversions, especially if some
            // inputs are not specified
            const euler = PzLib.transformEulerV3dToBlenderShortest(obj.rotation,
                    _pGlob.eulerTmp);
            PzLib.transformCoordsSpace(euler, coordSystem, 'Y_UP_RIGHT');

            if (inputsUsed.x) euler.x = offset ? euler.x + coords.x : coords.x;
            if (inputsUsed.y) euler.y = offset ? euler.y + coords.y : coords.y;
            if (inputsUsed.z) euler.z = offset ? euler.z + coords.z : coords.z;

            /**
             * convert from Blender/Max default XYZ extrinsic order to v3d XYZ
             * intrinsic with reversion (XYZ -> ZYX) and axes swizzling (ZYX -> YZX)
             */
            euler.order = "YZX";
            euler.reorder(obj.rotation.order);
            obj.rotation.copy(euler);

        } else if (mode === 'rotation' && coordSystem == 'Y_UP_RIGHT') {
            // Maya coordinates

            // Use separate rotation interface to fix ambiguous rotations for Maya,
            // might as well do the same for Blender/Max.

            const rotUI = PzLib.RotationInterface.initObject(obj);
            const euler = rotUI.getUserRotation(_pGlob.eulerTmp);
            // TODO(ivan): this probably needs some reasonable wrapping
            if (inputsUsed.x) euler.x = offset ? euler.x + coords.x : coords.x;
            if (inputsUsed.y) euler.y = offset ? euler.y + coords.y : coords.y;
            if (inputsUsed.z) euler.z = offset ? euler.z + coords.z : coords.z;

            rotUI.setUserRotation(euler);
            rotUI.getActualRotation(obj.rotation);
        } else {
            if (inputsUsed.x) setObjProp(obj, "x", coords.x);
            if (inputsUsed.y) setObjProp(obj, "y", coords.y);
            if (inputsUsed.z) setObjProp(obj, "z", coords.z);
        }

        obj.updateWorldMatrix(false, true);
    }

}

// loadMedia puzzle
function loadMedia_HTML5(url) {

    var elems = _pGlob.mediaElements;
    if (!(url in elems)) {
        elems[url] = new PzLib.MediaHTML5().load(url);
    }
    return elems[url];
}

// volume puzzle
function volume(mediaElem, volume) {
    const mediaElems = (Array.isArray(mediaElem) ? mediaElem : [mediaElem]).filter(elem => elem);

    volume = Number(volume);
    if (Number.isNaN(volume)) {
        return;
    }

    mediaElems.forEach(mediaElem => {
        mediaElem.setVolume(v3d.MathUtils.clamp(volume, 0.0, 1.0));
    });
}

// loadMedia puzzle
function loadMedia_WebAudio(url) {
    if (!v3d.Detector.checkWebAudio()) {
        if (!_pGlob.noWebAudioReported) {
            _pGlob.noWebAudioReported = true;
            console.error('load sound: Web Audio API not supported');
        }
        return null;
    }

    var elems = _pGlob.mediaElements;
    if (!(url in elems)) {
        elems[url] = new PzLib.AudioWebAudio().load(url);
    }
    return elems[url];
}

// everyFrame puzzle
function registerEveryFrame(callback) {
    if (typeof callback == 'function') {
        appInstance.renderCallbacks.push(callback);
        if (PL.editorRenderCallbacks)
            PL.editorRenderCallbacks.push([appInstance, callback]);
    }
}

function mathRandomInt(a, b) {
  if (a > b) {
    // Swap a and b to ensure a is smaller.
    var c = a;
    a = b;
    b = c;
  }
  return Math.floor(Math.random() * (b - a + 1) + a);
}

// Describe this function...
function Randomize_Empty() {
    random_numder = mathRandomInt(1, 6);
    if (random_numder == 1) {
        empty_index = mathRandomInt(1, 9);
        random_empty = 'Empty.00' + String(empty_index);
    } else if (random_numder == 2) {
        empty_index = mathRandomInt(10, 99);
        random_empty = 'Empty.0' + String(empty_index);
    } else if (random_numder >= 3) {
        empty_index = mathRandomInt(100, 384);
        random_empty = 'Empty.' + String(empty_index);
    }
    if (emptys_distance[empty_index] < 30) {
        Randomize_Empty();
    }
}

// removeHTMLElement puzzle
function removeHTMLElement(id, isParent) {
    const elem = PzLib.getElement(id, isParent);
    if (elem && elem.parentNode) {
        elem.parentNode.removeChild(elem);
        _pGlob.htmlElements.delete(elem);
    }
}

// eventHTMLElem puzzle
function eventHTMLElem(eventType, ids, isParent, callback) {
    var elems = PzLib.getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem)
            continue;

        PzLib.bindListener(elem, eventType, callback);
    }
}

// pauseSound puzzle
function pauseSound(mediaElem) {
    const mediaElems = (Array.isArray(mediaElem) ? mediaElem : [mediaElem]).filter(elem => elem);
    mediaElems.forEach(mediaElem => {
        mediaElem.pause();
    });
}

// playSound puzzle
function playSound(mediaElem, loop) {
    const mediaElems = (Array.isArray(mediaElem) ? mediaElem : [mediaElem]).filter(elem => elem);
    mediaElems.forEach(mediaElem => {
        mediaElem.setLoop(loop);
        if (mediaElem.audio)
            mediaElem.audio.context.resume();
        mediaElem.play();
    });
}

// setInterval puzzle
function registerInterval(timeout, callback) {
    var timerId = window.setInterval(function() { callback(timerId) }, 1000 * timeout);
}

// featureAvailable puzzle
function featureAvailable(feature) {

    const userAgent = window.navigator.userAgent;
    const platform = window.navigator.platform;
    let canvas, gl;

    switch (feature) {
    case 'MOBILE':
        return (/Android|webOS|BlackBerry/i.test(userAgent) || v3d.Detector.checkIOS());

    case 'ANDROID':
        return /Android/i.test(userAgent);
    case 'IOS':
        return v3d.Detector.checkIOS();
    case 'WINDOWS':
        return ['Win32', 'Win64', 'Windows', 'WinCE'].indexOf(platform) !== -1;
    case 'MACOS':
        return (['Macintosh', 'MacIntel', 'MacPPC', 'Mac68K'].indexOf(platform) !== -1 && !v3d.Detector.checkIOS());
    case 'CHROMEOS':
        return /(CrOS)/.test(userAgent);
    case 'LINUX':
        return /Linux/.test(platform);

    case 'CHROME':
        // Chromium based
        return (!!window.chrome && !/Edge/.test(navigator.userAgent));
    case 'FIREFOX':
        return /Firefox/.test(navigator.userAgent);
    case 'IE':
        return /Trident/.test(navigator.userAgent);
    case 'EDGE':
        return /Edge/.test(navigator.userAgent);
    case 'SAFARI':
        return (/Safari/.test(navigator.userAgent) && !/Chrome/.test(navigator.userAgent));

    case 'TOUCH':
        return v3d.Detector.isTouchDevice();
    case 'RETINA':
        return window.devicePixelRatio >= 2;
    case 'HDR':
        return appInstance.useHDR;
    case 'WEBAUDIO':
        return v3d.Detector.checkWebAudio();
    case 'WEBGL':
        canvas = document.createElement('canvas');
        gl = canvas.getContext('webgl')
        return !!gl;
    case 'WEBGL2':
        canvas = document.createElement('canvas');
        gl = canvas.getContext('webgl2')
        return !!gl;
    case 'WOOCOMMERCE':
        try {
            const woo_fun = window.parent.v3d_woo_get_product_info || window.parent.parent.v3d_woo_get_product_info;
            return !!woo_fun;
        } catch (e) {
            // blocked cross-origin access
            return false;
        }
    case 'DO_NOT_TRACK':
        if (navigator.doNotTrack == '1' || window.doNotTrack == '1')
            return true;
        else
            return false;
    default:
        return false;
    }

}

// Describe this function...
function Move_Left() {
    if (farmer_position_prev == farmer_posotion_next && game_started == 1) {
        farmer_posotion_next = farmer_posotion_next + 1;
        move_steps = (farmer_posotion_next - farmer_position_prev) / 10;
    }
}

// removeObject puzzles
function removeObject(objSelector) {
    const objNames = PzLib.retrieveObjectNames(objSelector);

    for (let i = 0; i < objNames.length; i++) {
        const objName = objNames[i]
        if (!objName)
            continue;
        const obj = PzLib.getObjectByName(objName);
        if (!obj || !obj.parent)
            continue;

        PzLib.removeObject(obj, objName);
    }
}

// Describe this function...
function Move_Right() {
    if (farmer_position_prev == farmer_posotion_next && game_started == 1) {
        farmer_posotion_next = farmer_posotion_next - 1;
        move_steps = (farmer_posotion_next - farmer_position_prev) / 10;
    }
}

// initFullscreen puzzle
function initFullscreen(id, isParent, enterCb, exitCb, unavailCb) {
    const elem = PzLib.getElement(id, isParent);
    if (!elem)
        return;

    const doc = isParent ? parent.document : document;
    if (!(doc.fullscreenEnabled || doc.webkitFullscreenEnabled)) {
        unavailCb();
        return;
    }

    function fullscreenClickCb() {
        event.stopPropagation();
        if (doc.fullscreenElement || doc.webkitFullscreenElement) {
            exitFullscreen();
        } else {
            requestFullscreen(doc.body);
        }
    }
    PzLib.bindListener(elem, 'click', fullscreenClickCb);

    function changeFullscreen(event) {
        if (doc.fullscreenElement || doc.webkitFullscreenElement)
            enterCb(event);
        else
            exitCb(event);
    }

    PzLib.bindListener(doc, 'webkitfullscreenchange', changeFullscreen);
    PzLib.bindListener(doc, 'fullscreenchange', changeFullscreen);

    function requestFullscreen(fselem) {
        if (fselem.requestFullscreen)
            fselem.requestFullscreen();
        else if (fselem.webkitRequestFullscreen)
            fselem.webkitRequestFullscreen();
    }
    function exitFullscreen() {
        if (doc.exitFullscreen)
            doc.exitFullscreen();
        else if (doc.webkitExitFullscreen)
            doc.webkitExitFullscreen();
    }
}

// cloneObject puzzle
function cloneObject(objName, cloneMaterials, preserveGroups) {
    if (!objName)
        return;
    const obj = PzLib.getObjectByName(objName);
    if (!obj)
        return;

    const objNew = obj.clone(); // recursive
    objNew.name = PzLib.generateUniqueObjectName(obj.name);

    // assign unique names for multi-material object meshes
    const objsM = objNew.resolveMultiMaterial();
    if (objNew != objsM[0])
        for (let i = 0; i < objsM.length; i++)
            objsM[i].name = objNew.name + 'MatMesh' + i;

    if (cloneMaterials) {
        objNew.traverse(o => {
            if (o.material) {
                o.material = o.material.clone();
            }
        });
    }

    if (preserveGroups) {
        const oldGroups = [];
        obj.traverse(o => {
            oldGroups.push(o.groupNames);
        });

        let i = 0;
        objNew.traverse(o => {
            o.groupNames.push(...oldGroups[i]);
            i++;
        });
    }

    appInstance.scene.add(objNew);

    // add object to cache now to increase performance
    _pGlob.objCache.set(objNew.name, objNew);

    return objNew.name;
}

// makeParent puzzle
function makeParent(objName, targetObjName) {
    if (!objName)
        return;
    var obj = PzLib.getObjectByName(objName);
    if (!obj)
        return;
    if (targetObjName && targetObjName !== PzLib.LIST_NONE) {
        var targetObj = PzLib.getObjectByName(targetObjName);
        if (!targetObj)
            return;
    } else {
        obj.traverseAncestors(function(ancObj) {
            if (ancObj.type == "Scene")
                targetObj = ancObj;
        });
    }
    var matOffset = new v3d.Matrix4();
    matOffset.copy(targetObj.matrixWorld).invert();
    matOffset.multiply(obj.matrixWorld);
    matOffset.decompose(obj.position, obj.quaternion, obj.scale);
    targetObj.add(obj);

    obj.updateWorldMatrix(false, true);
}

// snapToObject puzzle
function snapToObject(objName, targetObjName) {
    if (!objName || !targetObjName)
        return;
    var obj = PzLib.getObjectByName(objName);
    var targetObj = PzLib.getObjectByName(targetObjName);
    if (!obj || !targetObj)
        return;
    obj.copyTransform(targetObj);
    obj.updateWorldMatrix(false, true);
}

// getGamepadProp puzzle
function getGamepadProp(index, prop, controlIndex) {

    if (_pGlob.xrSessionAcquired) {
        var controller = appInstance.xrControllers[index];

        if (controller && controller.userData.inputSource &&
                controller.userData.inputSource.gamepad)
            var gamepad = controller.userData.inputSource.gamepad;
        else
            var gamepad = undefined;

    } else {
        var gamepad = navigator.getGamepads()[index];
    }

    switch (prop) {
    case 'AXIS':
        if (gamepad)
            return (gamepad.axes[controlIndex] || 0);
        else
            return 0;

    case 'BUTTON':
        if (gamepad) {
            var button = gamepad.buttons[controlIndex];

            if (button)
                return button.pressed;
            else
                return false;
        } else {
            return false;
        }

    case 'ANALOG_BUTTON':
        if (gamepad) {
            var button = gamepad.buttons[controlIndex];

            if (button)
                return button.value;
            else
                return 0.0;
        } else {
            return 0.0;
        }

    case 'ID':
        if (gamepad)
            return gamepad.id;
        else
            return '';

    case 'CONNECTION_STATUS':
        if (gamepad)
            return gamepad.connected;
        else
            return false;

    case 'TIMESTAMP':
        if (gamepad)
            return gamepad.timestamp;
        else
            return 0.0;

    case 'MAPPING':
        if (gamepad)
            return gamepad.mapping;
        else
            return '';

    case 'DEBUG_INFO':
        if (gamepad) {

            var axes = gamepad.axes;
            var axesValues = []

            for (var i = 0; i < axes.length; i++) {
                axesValues.push(Math.round(axes[i] * 1000) / 1000);
            }

            var buttons = gamepad.buttons;
            var btnsPressed = [];
            var btnsValues = [];

            for (var i = 0; i < buttons.length; i++) {
                btnsPressed.push(buttons[i].pressed ? '☑' : '☐');
                btnsValues.push(Math.round(buttons[i].value * 1000) / 1000);
            }

            return 'Index: ' + index + '\n' +
                   'Connected: ' + (gamepad.connected ? 'Yes' : 'No') + '\n' +
                   'ID: ' + (gamepad.id ? gamepad.id : 'N/A') + '\n' +
                   'Axes: ' + String(axesValues) + '\n' +
                   'Buttons: ' + String(btnsPressed) + '\n' +
                   'Analog Buttons: ' + String(btnsValues) + '\n' +
                   'Timestamp: ' + (gamepad.timestamp ? gamepad.timestamp.toFixed(3) : 0);
        } else {
            return 'Gamepad not available';
        }
    }

}

// Describe this function...
function score_time_counting(add_time, add_score) {
    scores = scores + add_score;
    time = time + add_time;
    setHTMLElemAttribute('innerHTML', 'Scores: ' + String(scores), 'scores', false);
    setHTMLElemAttribute('innerHTML', 'Time: ' + String(time), 'time', false);
}

// Describe this function...
function fruits_counting(index) {
    if (emptys_with_fruits[index].charAt(0) == 'a') {
        fruit_count[0] = fruit_count[0] + 1;
        setHTMLElemAttribute('innerHTML', fruit_count[0], 'apple_count', false);
        playSound(loadMedia_WebAudio('sounds/fruit_pick_1.mp3'), false);
        score_time_counting(4, 2);
    } else if (emptys_with_fruits[index].charAt(0) == 'c') {
        fruit_count[1] = fruit_count[1] + 1;
        setHTMLElemAttribute('innerHTML', fruit_count[1], 'cherry_count', false);
        playSound(loadMedia_WebAudio('sounds/fruit_pick_2.mp3'), false);
        score_time_counting(-1, 5);
    } else if (emptys_with_fruits[index].charAt(0) == 'p') {
        fruit_count[2] = fruit_count[2] + 1;
        setHTMLElemAttribute('innerHTML', fruit_count[2], 'pear_count', false);
        playSound(loadMedia_WebAudio('sounds/fruit_pick_3.mp3'), false);
        score_time_counting(2, 3);
    } else if (emptys_with_fruits[index].charAt(0) == 's') {
        fruit_count[3] = fruit_count[3] + 1;
        playSound(loadMedia_WebAudio('sounds/fruit_pick_4.mp3'), false);
        setHTMLElemAttribute('innerHTML', fruit_count[3], 'strawberry_count', false);
        score_time_counting(-3, 10);
    }
}

// getEventProperty puzzle
function getEventProperty(prop, event) {
    if (typeof event != "undefined") {
        switch (prop) {
            case 'target.checked':
                return event.target.checked;
            case 'target.id':
                return event.target.id;
            case 'target.value':
                return event.target.value;
            case 'touches.length':
                return event.touches ? event.touches.length : 0;
            case 'touches[0].pageX':
                return event.touches[0].pageX;
            case 'touches[0].pageY':
                return event.touches[0].pageY;
            case 'touches[1].pageX':
                return event.touches[1].pageX;
            case 'touches[1].pageY':
                return event.touches[1].pageY;
            case 'targetTouches.length':
                return event.targetTouches ? event.targetTouches.length : 0;
            case 'targetTouches[0].pageX':
                return event.targetTouches[0].pageX;
            case 'targetTouches[0].pageY':
                return event.targetTouches[0].pageY;
            case 'targetTouches[1].pageX':
                return event.targetTouches[1].pageX;
            case 'targetTouches[1].pageY':
                return event.targetTouches[1].pageY;
            default:
                return event[prop];
        }
    }
}

// distanceBetweenObjects puzzle
function getDistanceBetweenObjects(objName1, objName2) {
    if (!objName1 || !objName2)
        return;
    var obj1 = PzLib.getObjectByName(objName1);
    var obj2 = PzLib.getObjectByName(objName2);
    if (!obj1 || !obj2)
        return;
    return obj1.getWorldPosition(_pGlob.vec3Tmp).distanceTo(obj2.getWorldPosition(_pGlob.vec3Tmp2));
}

// setCameraParam puzzle
function setCameraParam(type, camSelector, param) {

    const camNames = PzLib.retrieveObjectNames(camSelector);

    camNames.forEach(function(camName) {
        if (!camName)
            return;

        var cam = PzLib.getObjectByName(camName);
        if (!cam || !cam.isCamera) return;

        if (!(cam.isPerspectiveCamera || cam.isOrthographicCamera)) {
            console.error('set camera param puzzle: Incompatible camera type, have to be perspective or orthographic');
            return;
        }

        let isSetOrbitParam = false;
        let isSetFirstpersonParam = false;

        switch (type) {
            case 'ORBIT_MIN_DISTANCE_PERSP':
            case 'ORBIT_MAX_DISTANCE_PERSP':
            case 'ORBIT_MIN_ZOOM_ORTHO':
            case 'ORBIT_MAX_ZOOM_ORTHO':
            case 'ORBIT_MIN_VERTICAL_ANGLE':
            case 'ORBIT_MAX_VERTICAL_ANGLE':
            case 'ORBIT_MIN_HORIZONTAL_ANGLE':
            case 'ORBIT_MAX_HORIZONTAL_ANGLE':
            case 'ORBIT_ALLOW_TURNOVER':
                isSetOrbitParam = true;
                break;
            case 'ENABLE_COLLISIONS':
                isSetFirstpersonParam = true;
                break;
        }

        let isSetControlsParam = (['ROTATION_SPEED', 'MOVEMENT_SPEED', 'ALLOW_PANNING', 'ALLOW_ZOOM', 'ALLOW_CTRL_ZOOM', 'KEYBOARD_CONTROLS'].includes(type) || isSetOrbitParam || isSetFirstpersonParam);

        if (isSetControlsParam) {
            if (!cam.controlSettings) {
                console.error('set camera param puzzle: The "' + camName +'" camera has no control settings assigned');
                return;
            } else if ((isSetOrbitParam && cam.controlSettings.type != 'ORBIT') ||
                    (isSetFirstpersonParam && cam.controlSettings.type != 'FIRST_PERSON')) {
                console.error('set camera param puzzle: Incompatible camera controls: ' + cam.controlSettings.type);
                return;
            }
        }

        switch (type) {
            case 'FIELD_OF_VIEW':
                if (cam.isPerspectiveCamera) {
                    cam.fov = param;
                    cam.updateProjectionMatrix();
                } else {
                    console.error('set camera param puzzle: Incompatible camera type, have to be perspective');
                    return;
                }
                break;
            case 'ORTHO_SCALE':
                if (cam.isOrthographicCamera) {
                    cam.zoom = param;
                    cam.updateProjectionMatrix();
                } else {
                    console.error('set camera param puzzle: Incompatible camera type, have to be orthographic');
                    return;
                }
                break;
            case 'ROTATION_SPEED':
                cam.controlSettings.rotateSpeed = param;
                break;
            case 'MOVEMENT_SPEED':
                cam.controlSettings.moveSpeed = param;
                break;
            case 'ALLOW_PANNING':
                cam.controlSettings.enablePan = param;
                break;
            case 'ALLOW_ZOOM':
                cam.controlSettings.enableZoom = param;
                break;
            case 'ALLOW_CTRL_ZOOM':
                cam.controlSettings.enableCtrlZoom = param;
                break;
            case 'KEYBOARD_CONTROLS':
                cam.controlSettings.enableKeys = param;
                break;
            case 'ORBIT_MIN_DISTANCE_PERSP':
                if (cam.isPerspectiveCamera) {
                    cam.controlSettings.orbitMinDistance = param;
                } else {
                    console.error('set camera param puzzle: Incompatible camera type, have to be perspective');
                    return;
                }
                break;
            case 'ORBIT_MAX_DISTANCE_PERSP':
                if (cam.isPerspectiveCamera) {
                    cam.controlSettings.orbitMaxDistance = param;
                } else {
                    console.error('set camera param puzzle: Incompatible camera type, have to be perspective');
                    return;
                }
                break;
            case 'ORBIT_MIN_ZOOM_ORTHO':
                if (cam.isOrthographicCamera) {
                    cam.controlSettings.orbitMinZoom = param;
                } else {
                    console.error('set camera param puzzle: Incompatible camera type, have to be orthographic');
                    return;
                }
                break;
            case 'ORBIT_MAX_ZOOM_ORTHO':
                if (cam.isOrthographicCamera) {
                    cam.controlSettings.orbitMaxZoom = param;
                } else {
                    console.error('set camera param puzzle: Incompatible camera type, have to be orthographic');
                    return;
                }
                break;
            case 'ORBIT_MIN_VERTICAL_ANGLE':
                cam.controlSettings.orbitMinPolarAngle = v3d.MathUtils.degToRad(param);
                break;
            case 'ORBIT_MAX_VERTICAL_ANGLE':
                cam.controlSettings.orbitMaxPolarAngle = v3d.MathUtils.degToRad(param);
                break;
            case 'ORBIT_MIN_HORIZONTAL_ANGLE':
                cam.controlSettings.orbitMinAzimuthAngle = v3d.MathUtils.degToRad(param);
                break;
            case 'ORBIT_MAX_HORIZONTAL_ANGLE':
                cam.controlSettings.orbitMaxAzimuthAngle = v3d.MathUtils.degToRad(param);
                break;
            case 'ORBIT_ALLOW_TURNOVER':
                cam.controlSettings.orbitEnableTurnover = param;
                break;
            case 'ENABLE_COLLISIONS':
                cam.controlSettings.enableCollisions = param;
                break;
            case 'CLIP_START':
                cam.near = param;
                cam.updateProjectionMatrix();
                break;
            case 'CLIP_END':
                cam.far = param;
                cam.updateProjectionMatrix();
                break;
        }

        if (isSetControlsParam)
            appInstance.enableControls();

    });
}

// tweenCamera puzzle
function tweenCamera(posOrObj, targetOrObj, duration, doSlot, movementType) {
    var camera = appInstance.getCamera();

    if (Array.isArray(posOrObj)) {
        var worldPos = _pGlob.vec3Tmp.fromArray(posOrObj);
        worldPos = PzLib.transformCoordsSpace(worldPos,
                PzLib.getSceneCoordSystem(), 'Y_UP_RIGHT');
    } else if (posOrObj) {
        var posObj = PzLib.getObjectByName(posOrObj);
        if (!posObj) return;
        var worldPos = posObj.getWorldPosition(_pGlob.vec3Tmp);
    } else {
        // empty input means: don't change the position
        var worldPos = camera.getWorldPosition(_pGlob.vec3Tmp);
    }

    if (Array.isArray(targetOrObj)) {
        var worldTarget = _pGlob.vec3Tmp2.fromArray(targetOrObj);
        worldTarget = PzLib.transformCoordsSpace(worldTarget,
                PzLib.getSceneCoordSystem(), 'Y_UP_RIGHT');
    } else {
        var targObj = PzLib.getObjectByName(targetOrObj);
        if (!targObj) return;
        var worldTarget = targObj.getWorldPosition(_pGlob.vec3Tmp2);
    }

    duration = Math.max(0, duration);

    if (appInstance.controls && appInstance.controls.tween) {
        // orbit and flying cameras
        if (!appInstance.controls.inTween) {
            appInstance.controls.tween(worldPos, worldTarget, duration, doSlot,
                    movementType);
        }
    } else {
        // TODO: static camera, just position it for now
        if (camera.parent) {
            camera.parent.worldToLocal(worldPos);
        }
        camera.position.copy(worldPos);
        camera.lookAt(worldTarget);
        doSlot();
    }
}

// show and hide puzzles
function changeVis(objSelector, bool) {
    var objNames = PzLib.retrieveObjectNames(objSelector);

    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i]
        if (!objName)
            continue;
        var obj = PzLib.getObjectByName(objName);
        if (!obj)
            continue;
        obj.visible = bool;
        obj.resolveMultiMaterial().forEach(function(objR) {
            objR.visible = bool;
        });
    }
}

// rewindSound puzzle
function rewindSound(mediaElem) {
    const mediaElems = (Array.isArray(mediaElem) ? mediaElem : [mediaElem]).filter(elem => elem);
    mediaElems.forEach(mediaElem => {
        mediaElem.rewind();
    });
}

// Describe this function...
function start_game() {
    setHTMLElemStyle('display', 'none', 'lsplash_screen_ocker', false);
    setHTMLElemStyle('display', 'block', 'top_left_bar', false);
    setHTMLElemStyle('display', 'block', 'top_right_bar', false);
    tweenCamera('camera_point', 'lookat_point', 1, function() {
        setCameraParam('ORBIT_MAX_DISTANCE_PERSP', 'Camera', 10);
    }, 0);
    ground_speed = -0.2;
    fruits_max = 30;
    game_started = 1;
    time = 80;
    scores = 0;
    fruit_count[0] = 0;
    fruit_count[1] = 0;
    fruit_count[2] = 0;
    fruit_count[3] = 0;
    setHTMLElemAttribute('innerHTML', fruit_count[0], 'apple_count', false);
    setHTMLElemAttribute('innerHTML', fruit_count[1], 'cherry_count', false);
    setHTMLElemAttribute('innerHTML', fruit_count[2], 'pear_count', false);
    setHTMLElemAttribute('innerHTML', fruit_count[3], 'strawberry_count', false);
    if (featureAvailable('MOBILE')) {
        setHTMLElemStyle('display', 'block', 'left_button_container', false);
        setHTMLElemStyle('display', 'block', 'right_button_container', false);
    }
    for (let m = 1; m <= 384; m++) {
        if (emptys_with_fruits[m] != 'empty') {
            changeVis(emptys_with_fruits[m], false);
            emptys_with_fruits[m] = 'empty';
        }
    }
    setHTMLElemAttribute('innerHTML', 'Time: ' + String(time), 'time', true);
    setHTMLElemAttribute('innerHTML', 'Scores: ' + String(scores), 'scores', true);
    operateAnimation('PLAY', 'farmer_armature', null, null, 'LoopRepeat', 1, function() {}, false);
    playSound(loadMedia_WebAudio('sounds/steps.mp3'), true);
    rewindSound(loadMedia_HTML5('sounds/soundtrack.mp3'));
    playSound(loadMedia_HTML5('sounds/soundtrack.mp3'), true);
    playSound(loadMedia_HTML5('sounds/ambient_sound.mp3'), true);
}


/* Splash Screen */

/* Score Info Panel */

addHTMLElement('div', 'lsplash_screen_ocker', 'TO', ['CONTAINER'], false);
setHTMLElemAttribute('style', "position: absolute; background-color: transparent; width: 100%; height: 100%;", 'lsplash_screen_ocker', false);

createCSSRule('.top-left-bar', "position: absolute; background-color: transparent; width: auto; height: 180px; min-width: 530px; padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);", false, '');

/* Fullscreen and Help Buttons */

/* Controll Button */

createCSSRule('.top-right-bar', "position: absolute; width: 140px; height: 80px; top: 0px; right: 0px; z-index: 11; padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);", false, '');

/* Help Desk */

createCSSRule('.controll-button', "width: 60px; height: 60px; background-size: contain; background-repeat: no-repeat; margin: 10px 10px;", false, '');

createCSSRule('.tile-container', "position: absolute; background-color: transparent; width: 100%; height: 380px; top: 50%; margin-top: -190px;", false, '');
addHTMLElement('div', 'tile_container', 'TO', 'lsplash_screen_ocker', false);
setHTMLElemAttribute('className', 'tile-container', 'tile_container', false);

/* Final Score Bar */

setHTMLElemAttribute('style', "position: absolute; width: 100%; height: 100%; z-index: 10;", 'help_locker', false);
addHTMLElement('div', 'help_locker', 'TO', ['CONTAINER'], false);
setHTMLElemStyle('display', 'none', 'help_locker', false);

addHTMLElement('div', 'top_left_bar', 'TO', ['CONTAINER'], false);
setHTMLElemAttribute('className', 'top-left-bar', 'top_left_bar', false);
setHTMLElemStyle('display', 'none', 'top_left_bar', false);

addHTMLElement('div', 'final_score_locker', 'TO', ['CONTAINER'], false);
setHTMLElemAttribute('style', "position: absolute; width: 100%; height: 100%; z-index: 12;", 'final_score_locker', false);
setHTMLElemStyle('display', 'none', 'final_score_locker', false);

createCSSRule('.left-button-container', "position: absolute; display: none; width: 80px; height: 80px; bottom: 0px; left: 0px; padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);", false, '');
addHTMLElement('div', 'left_button_container', 'TO', ['CONTAINER'], false);
setHTMLElemAttribute('className', 'left-button-container', 'left_button_container', false);
setHTMLElemStyle('display', 'none', 'left_button_container', false);

addHTMLElement('div', 'top_right_bar', 'TO', ['CONTAINER'], false);
setHTMLElemAttribute('className', 'top-right-bar', 'top_right_bar', false);
setHTMLElemStyle('display', 'none', 'top_right_bar', false);
createCSSRule('.manager-button', "position: static; float: right; background-size: contain; background-repeat: no-repeat; width: 60px; height: 60px; margin: 5px; cursor: pointer;", false, '');

createCSSRule('.fruits-counts-container', "background-color: transparent; width: auto; height: 60px; min-width: 360px;", false, '');
addHTMLElement('div', 'fruits_counts_container', 'TO', 'top_left_bar', false);
setHTMLElemAttribute('className', 'fruits-counts-container', 'fruits_counts_container', false);

createCSSRule('.help-background', "position: absolute; background: linear-gradient(45deg, rgba(255,169,21,1) 0%, rgba(250,200,113,1) 100%); width: 600px; height: 500px; left: 50%; margin-left: -300px; top: 50%; margin-top: -200px; box-shadow: 0px 0px 10px black; border-radius: 12px; border: 3px solid #b87400;", false, '');
addHTMLElement('div', 'help_background', 'TO', 'help_locker', false);
setHTMLElemAttribute('className', 'help-background', 'help_background', false);

createCSSRule('.tile-image', "position: absolute; background-color: transparent; width: 600px; height: 360px; top: 0px; left: 50%; margin-left: -300px;", false, '');
addHTMLElement('img', 'tile_image', 'TO', 'tile_container', false);
setHTMLElemAttribute('className', 'tile-image', 'tile_image', false);
setHTMLElemAttribute('src', 'media/title.png', 'tile_image', false);

createCSSRule('.score-bar-container', "position: absolute; background-color: transparent; width: 100%; height: 480px; top: 50%; margin-top: -225px;", false, '');
addHTMLElement('div', 'score_bar_container', 'TO', 'final_score_locker', false);
setHTMLElemAttribute('className', 'score-bar-container', 'score_bar_container', false);

createCSSRule('.fruit-image', "float: left; background-size: contain; background-repeat: no-repeat; width: 60px; height: 60px; border: none;", false, '');

addHTMLElement('div', 'button_left', 'TO', 'left_button_container', false);
setHTMLElemAttribute('className', 'controll-button', 'button_left', false);
setHTMLElemAttribute('style', "background-image: url(\'media/step_right.svg\');", 'button_left', false);

addHTMLElement('div', 'fullscreen_button', 'TO', 'top_right_bar', false);
setHTMLElemAttribute('className', 'manager-button', 'fullscreen_button', false);
setHTMLElemStyle('backgroundImage', 'url(\'media/fullscreen_on.svg\')', 'fullscreen_button', false);

addHTMLElement('img', 'score_bar_image', 'TO', 'score_bar_container', false);
setHTMLElemAttribute('className', 'tile-image', 'score_bar_image', false);
setHTMLElemAttribute('src', 'media/title.png', 'score_bar_image', false);

createCSSRule('.button', "position: absolute; background-image: url(\'media/button.svg\'); width: 134px; height: 34px; bottom: 0px; left: 50%; margin-left: -67px; cursor: pointer; font-family: ChangaOne; color: white; text-align: center; font-size: 18px; line-height: 2em;", false, '');
addHTMLElement('div', 'startout_button', 'TO', 'tile_container', false);
setHTMLElemAttribute('className', 'button', 'startout_button', false);
setHTMLElemAttribute('innerHTML', 'Start Out', 'startout_button', false);

createCSSRule('.right-button-container', "position: absolute; display: none; width: 80px; height: 80px; bottom: 0px; right: 0px; padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);", false, '');
addHTMLElement('div', 'right_button_container', 'TO', ['CONTAINER'], false);
setHTMLElemAttribute('className', 'right-button-container', 'right_button_container', false);
setHTMLElemStyle('display', 'none', 'right_button_container', false);

createCSSRule('.help-header', "color: black; font-family: ChangaOne; text-align: center; font-weight: normal; font-size: 26px;", false, '');
addHTMLElement('h1', 'help_header', 'TO', 'help_background', false);
setHTMLElemAttribute('className', 'help-header', 'help_header', false);
setHTMLElemAttribute('innerHTML', 'What to DO?', 'help_header', false);

addHTMLElement('img', 'apple-image', 'TO', 'fruits_counts_container', false);
setHTMLElemAttribute('className', 'fruit-image', 'apple-image', false);
setHTMLElemAttribute('src', 'media/apple_icon.svg', 'apple-image', false);

addHTMLElement('div', 'help_button', 'TO', 'top_right_bar', false);
setHTMLElemAttribute('className', 'manager-button', 'help_button', false);
setHTMLElemStyle('backgroundImage', 'url(\'media/help.svg\')', 'help_button', false);

createCSSRule('.score-bar-total-score', "position: absolute; top: 360px; left: 50%; margin-left: -150px; width: 300px; height: 60px; font-family: ChangaOne; color: #bd3803; font-size: 40px; text-align: center; line-height: 1.5em; background: linear-gradient(45deg, rgba(255,169,21,1) 0%, rgba(250,200,113,1) 100%); border-radius: 30px; border: 3px solid #b87400;", false, '');
addHTMLElement('div', 'score_bar_total_score', 'TO', 'score_bar_container', false);
setHTMLElemAttribute('className', 'score-bar-total-score', 'score_bar_total_score', false);
setHTMLElemAttribute('innerHTML', 'Scores: 000', 'score_bar_total_score', false);

createCSSRule('.count-text', "float: left; font-family: ChangaOne; color: black; font-size: 40px; width: auto; min-width: 72px; height: 60px; line-height: 1.6em;", false, '');

createCSSRule('.help-discription', "color: black; font-family: Verdana; text-align: center; font-weight: lighter; font-size: 16px; padding: 15px;", false, '');
addHTMLElement('div', 'help_description_1', 'TO', 'help_background', false);
setHTMLElemAttribute('className', 'help-discription', 'help_description_1', false);
setHTMLElemAttribute('innerHTML', 'Simply collect the fruits as much as possible within the given time. Be advised that some of the fruits give you more score, but take away your time; while another give you additional time but less score.', 'help_description_1', false);

addHTMLElement('div', 'button_right', 'TO', 'right_button_container', false);
setHTMLElemAttribute('className', 'controll-button', 'button_right', false);
setHTMLElemAttribute('style', "background-image: url(\'media/step_left.svg\');", 'button_right', false);

addHTMLElement('div', 'apple_count', 'TO', 'fruits_counts_container', false);
setHTMLElemAttribute('className', 'count-text', 'apple_count', false);
setHTMLElemAttribute('innerHTML', '0', 'apple_count', false);

addHTMLElement('img', 'pear-image', 'TO', 'fruits_counts_container', false);
setHTMLElemAttribute('className', 'fruit-image', 'pear-image', false);
setHTMLElemAttribute('src', 'media/pear_icon.svg', 'pear-image', false);

addHTMLElement('div', 'help_description_2', 'TO', 'help_background', false);
setHTMLElemAttribute('className', 'help-discription', 'help_description_2', false);
setHTMLElemAttribute('innerHTML', 'Use <b>arrows (← →)</b> or <b>A</b> and <b>D</b> keys to move the character, drag with the mouse to view more.', 'help_description_2', false);

addHTMLElement('div', 'pear_count', 'TO', 'fruits_counts_container', false);
setHTMLElemAttribute('className', 'count-text', 'pear_count', false);
setHTMLElemAttribute('innerHTML', '0', 'pear_count', false);

addHTMLElement('div', 'startagain_button', 'TO', 'score_bar_container', false);
setHTMLElemAttribute('className', 'button', 'startagain_button', false);
setHTMLElemAttribute('innerHTML', 'Try Again', 'startagain_button', false);

addHTMLElement('img', 'cherry-image', 'TO', 'fruits_counts_container', false);
setHTMLElemAttribute('className', 'fruit-image', 'cherry-image', false);
setHTMLElemAttribute('src', 'media/cherry_icon.svg', 'cherry-image', false);

createCSSRule('.score-help', "position: absolute; width: 300px; height: 250px; left: 50%; margin-left: -150px; background-image: url(\'media/fruits-help.svg\'); background-size: contain; background-repeat: no-repeat; background-position: center;", false, '');
addHTMLElement('div', 'score_help', 'TO', 'help_background', false);
setHTMLElemAttribute('className', 'score-help', 'score_help', false);

addHTMLElement('div', 'cherry_count', 'TO', 'fruits_counts_container', false);
setHTMLElemAttribute('className', 'count-text', 'cherry_count', false);
setHTMLElemAttribute('innerHTML', '0', 'cherry_count', false);

addHTMLElement('img', 'strawberry-image', 'TO', 'fruits_counts_container', false);
setHTMLElemAttribute('className', 'fruit-image', 'strawberry-image', false);
setHTMLElemAttribute('src', 'media/strawberry_icon.svg', 'strawberry-image', false);

addHTMLElement('div', 'strawberry_count', 'TO', 'fruits_counts_container', false);
setHTMLElemAttribute('className', 'count-text', 'strawberry_count', false);
setHTMLElemAttribute('innerHTML', '0', 'strawberry_count', false);

createCSSRule('.scores', "float: none; top: 60px; left: 10px;", false, '');
addHTMLElement('div', 'scores', 'TO', 'top_left_bar', false);
setHTMLElemAttribute('className', 'count-text scores', 'scores', false);
setHTMLElemAttribute('innerHTML', 'Scores: 0', 'scores', false);

createCSSRule('.time', "float: none; top: auto; left: auto;", false, '');
addHTMLElement('div', 'time', 'TO', 'top_left_bar', false);
setHTMLElemAttribute('className', 'count-text time', 'time', false);
setHTMLElemAttribute('innerHTML', 'Time: 80', 'time', false);

media_common = 'screen and (max-width: 800px)';
media_portrait = 'screen and (max-width: 450px) and (orientation: portrait)';
media_width_max600px = 'screen and (max-width: 600px) and (orientation: portrait)';
media_height_max600px = 'screen and (max-height: 600px) and (orientation: landscape)';

/* Splash Screen Mobile Common */
createCSSRule('.tile-container', "height: 220px; top: 50%; margin-top: -110px;", false, media_common);

/* Fullscreen and Help Buttons Mobile Common */
createCSSRule('.top-right-bar', "width: 100px; height: 60px;", false, media_common);
createCSSRule('.manager-button', "width: 40px; height: 40px;", false, media_common);

/* Score Info Panel  Mobile Common */

/* Controll Button  Mobile Common */
createCSSRule('.left-button-container', "display: block;", false, media_common);
createCSSRule('.right-button-container', "display: block;", false, media_common);

/* Help Desk Mobile Common */

createCSSRule('.top-left-bar', "height: 180px; min-width: 340px;", false, media_common);

/* Final Score Bar Mobile Common */

createCSSRule('.tile-image', "width: 300px; height: 180px; left: 50%; margin-left: -150px;", false, media_common);

createCSSRule('.help-header', "margin: 8px 0px;", false, media_width_max600px);

createCSSRule('.fruit-image', "width: 40px; height: 40px;", false, media_common);

createCSSRule('.score-bar-container', "height: 270px; top: 50%; margin-top: -135px;", false, media_common);

createCSSRule('.help-background', "width: 300px; height: 420px; left: 50%; margin-left: -150px; top: 50%; margin-top: -200px;", false, media_width_max600px);

createCSSRule('.count-text', "font-size: 30px; width: auto; min-width: 40px; height: auto; line-height: 1.5em;", false, media_common);

createCSSRule('.score-bar-total-score', "top: 180px; left: 50%; margin-left: -100px; width: 200px; height: 40px; font-size: 26px; line-height: 1.5em; border-radius: 20px;", false, media_common);

createCSSRule('.fruits-counts-container', "background-color: transparent; width: auto; height: 40px; min-width: 340px;", false, media_common);

createCSSRule('.help-discription', "font-size: 12px; padding: 4px;", false, media_width_max600px);

createCSSRule('.score-help', "width: 250px; height: 240px; margin-left: -125px;", false, media_width_max600px);

createCSSRule('.scores', "top: 40px;", false, media_common);

/* Help Desk Mobile Horizontal 600px */

createCSSRule('.time', "top: 80px;", false, media_common);

createCSSRule('.help-background', "width: 580px; height: 240px; left: 50%; margin-left: -290px; top: 50%; margin-top: -110px;", false, media_height_max600px);

/* Score Info Panel Mobile Portrait */

createCSSRule('.help-header', "text-align: center; width: 300px; margin: 8px 0px;", false, media_height_max600px);

createCSSRule('.top-left-bar', "height: 180px; min-width: 170px;", false, media_portrait);

createCSSRule('.fruits-counts-container', "background-color: transparent; width: 180px; height: auto; min-width: 180px;", false, media_portrait);

createCSSRule('.help-discription', "width: 300px; font-size: 14px; padding: 8px;", false, media_height_max600px);

createCSSRule('.score-help', "width: 250px; height: 240px; left: auto; margin-left: auto; right: 10px; top: 50%; margin-top: -125px;", false, media_height_max600px);

createCSSRule('.scores', "top: 90px; left: 2px;", false, media_portrait);

createCSSRule('.time', "top: 130px; left: 2px;", false, media_portrait);

operateAnimation('STOP', 'farmer_armature', null, null, 'AUTO', 1, function() {}, false);
emptys_with_fruits = [];
emptys_distance = [];
for (let i = 1; i <= 384; i++) {
    emptys_with_fruits[i] = 'empty';
}
farmers_position = 0;
farmer_position_prev = 0;
farmer_posotion_next = 0;
move_steps = 0;
setObjTransform('farmer_armature', false, 'position', [0, null, null], false);
fruits_max = 0;
fruits_amount = 0;
ground_speed = 0;
fruit_count = [0, 0, 0, 0];
game_started = 0;
scores = 0;
time = 0;
help_mode = 0;
volume(loadMedia_HTML5('sounds/ambient_sound.mp3'), 0.2);
volume(loadMedia_WebAudio('sounds/steps.mp3'), 0.3);
volume(loadMedia_WebAudio('sounds/tada.mp3'), 0.6);
volume(loadMedia_HTML5('sounds/soundtrack.mp3'), 0.2);
volume(loadMedia_WebAudio('sounds/fruit_pick_1.mp3'), 0.7);
volume(loadMedia_WebAudio('sounds/fruit_pick_2.mp3'), 0.7);
volume(loadMedia_WebAudio('sounds/fruit_pick_3.mp3'), 0.7);
volume(loadMedia_WebAudio('sounds/fruit_pick_4.mp3'), 0.7);

registerEveryFrame(function() {
    setObjTransform('ground', false, 'rotation', [ground_speed, '', ''], true);
    setObjTransform('clouds', false, 'rotation', ['', '', 0.03], true);
});

/* Cordova mobile */
eventHTMLElem('deviceready', ['DOCUMENT'], false, function(event) {
    removeHTMLElement('fullscreen-button', false);
});
eventHTMLElem('pause', ['DOCUMENT'], false, function(event) {
    game_started = 0;
    ground_speed_temp = ground_speed;
    ground_speed = 0;
    operateAnimation('STOP', 'farmer_armature', null, null, 'AUTO', 1, function() {}, false);
    pauseSound(loadMedia_WebAudio('sounds/steps.mp3'));
    pauseSound(loadMedia_HTML5('sounds/soundtrack.mp3'));
    pauseSound(loadMedia_HTML5('sounds/ambient_sound.mp3'));
});
eventHTMLElem('resume', ['DOCUMENT'], false, function(event) {
    game_started = 1;
    ground_speed = ground_speed_temp;
    operateAnimation('PLAY', 'farmer_armature', null, null, 'LoopRepeat', 1, function() {}, false);
    playSound(loadMedia_WebAudio('sounds/steps.mp3'), true);
    playSound(loadMedia_HTML5('sounds/soundtrack.mp3'), true);
    playSound(loadMedia_HTML5('sounds/ambient_sound.mp3'), true);
});

registerInterval(10, function() {
    if (game_started == 1 && ground_speed < 1) {
        fruits_max = fruits_max + 5;
        ground_speed = ground_speed - 0.01;
    }
});

registerInterval(1, function() {
    if (game_started == 1 && time > 0) {
        time = time - 1;
        setHTMLElemAttribute('innerHTML', 'Time: ' + String(time), 'time', false);
    } else if (game_started == 1 && time <= 0) {
        game_started = 0;
        ground_speed = 0;
        time = 0;
        operateAnimation('STOP', 'farmer_armature', null, null, 'AUTO', 1, function() {}, false);
        pauseSound(loadMedia_WebAudio('sounds/steps.mp3'));
        setHTMLElemStyle('display', 'block', 'final_score_locker', false);
        setHTMLElemAttribute('innerHTML', 'Scores: ' + String(scores), 'score_bar_total_score', false);
        pauseSound(loadMedia_HTML5('sounds/soundtrack.mp3'));
        playSound(loadMedia_WebAudio('sounds/tada.mp3'), false);
        setHTMLElemStyle('display', 'none', 'top_left_bar', false);
        setHTMLElemStyle('display', 'none', 'top_right_bar', false);
        if (featureAvailable('MOBILE')) {
            setHTMLElemStyle('display', 'none', 'left_button_container', false);
            setHTMLElemStyle('display', 'none', 'right_button_container', false);
        }
    }
});

eventHTMLElem('click', 'startout_button', false, function(event) {
    start_game();
});

registerEveryFrame(function() {
    for (let j = 1; j <= 9; j++) {
        if (emptys_distance[j] <= 0.5 && emptys_with_fruits[j] != 'empty') {
            removeObject(emptys_with_fruits[j]);
            fruits_counting(j);
            fruits_amount = fruits_amount - 1;
            emptys_with_fruits[j] = 'empty';
        }
    }
    for (let j = 10; j <= 99; j++) {
        if (emptys_distance[j] <= 0.5 && emptys_with_fruits[j] != 'empty') {
            removeObject(emptys_with_fruits[j]);
            fruits_counting(j);
            fruits_amount = fruits_amount - 1;
            emptys_with_fruits[j] = 'empty';
        }
    }
    for (let j = 100; j <= 384; j++) {
        if (emptys_distance[j] <= 0.5 && emptys_with_fruits[j] != 'empty') {
            removeObject(emptys_with_fruits[j]);
            fruits_counting(j);
            fruits_amount = fruits_amount - 1;
            emptys_with_fruits[j] = 'empty';
        }
    }
});

eventHTMLElem('click', 'startagain_button', false, function(event) {
    start_game();
    setHTMLElemStyle('display', 'none', 'final_score_locker', false);
});

eventHTMLElem('click', 'help_button', false, function(event) {
    if (help_mode == 0) {
        setHTMLElemStyle('display', 'block', 'help_locker', false);
        setHTMLElemStyle('display', 'none', 'top_left_bar', false);
        if (featureAvailable('MOBILE')) {
            setHTMLElemStyle('display', 'none', 'left_button_container', false);
            setHTMLElemStyle('display', 'none', 'right_button_container', false);
        }
        help_mode = 1;
        game_started = 0;
        ground_speed_temp = ground_speed;
        ground_speed = 0;
        operateAnimation('STOP', 'farmer_armature', null, null, 'AUTO', 1, function() {}, false);
        pauseSound(loadMedia_WebAudio('sounds/steps.mp3'));
        pauseSound(loadMedia_HTML5('sounds/soundtrack.mp3'));
    } else if (help_mode == 1) {
        setHTMLElemStyle('display', 'none', 'help_locker', false);
        setHTMLElemStyle('display', 'block', 'top_left_bar', false);
        if (featureAvailable('MOBILE')) {
            setHTMLElemStyle('display', 'block', 'left_button_container', false);
            setHTMLElemStyle('display', 'block', 'right_button_container', false);
        }
        help_mode = 0;
        game_started = 1;
        ground_speed = ground_speed_temp;
        operateAnimation('PLAY', 'farmer_armature', null, null, 'LoopRepeat', 1, function() {}, false);
        playSound(loadMedia_WebAudio('sounds/steps.mp3'), true);
        playSound(loadMedia_HTML5('sounds/soundtrack.mp3'), true);
    }
});

initFullscreen('fullscreen_button', false, function() {
    setHTMLElemStyle('backgroundImage', 'url(\'media/fullscreen_off.svg\')', 'fullscreen_button', false);
}, function() {
    setHTMLElemStyle('backgroundImage', 'url(\'media/fullscreen_on.svg\')', 'fullscreen_button', false);
}, function() {
    setHTMLElemStyle('display', 'none', 'fullscreen_button', false);
});

registerInterval(1, function() {
    if (fruits_max != fruits_amount) {
        random_numder = mathRandomInt(1, 4);
        if (random_numder == 1) {
            fruit_clone = cloneObject('apple', false, false);
        } else if (random_numder == 2) {
            fruit_clone = cloneObject('cherry', false, false);
        } else if (random_numder == 3) {
            fruit_clone = cloneObject('pear', false, false);
        } else if (random_numder == 4) {
            fruit_clone = cloneObject('strawberry', false, false);
        }
        Randomize_Empty();
        if (emptys_with_fruits[empty_index] == 'empty') {
            emptys_with_fruits[empty_index] = fruit_clone;
            makeParent(fruit_clone, random_empty);
            snapToObject(fruit_clone, random_empty);
            setObjTransform(fruit_clone, false, 'rotation', ['', mathRandomInt(1, 360), ''], true);
            fruits_amount = fruits_amount + 1;
        }
    }
});
registerEveryFrame(function() {
    if (getGamepadProp(0, 'CONNECTION_STATUS', '0') && getGamepadProp(0, 'MAPPING', '0') == 'standard') {
        if (gamepad_timestamp != getGamepadProp(0, 'TIMESTAMP', '0')) {
            if (farmers_position < 1 && getGamepadProp(0, 'BUTTON', '14')) {
                Move_Left();
            } else if (getGamepadProp(0, 'BUTTON', '15') && farmers_position > -1) {
                Move_Right();
            }
        }
    }
    gamepad_timestamp = getGamepadProp(0, 'TIMESTAMP', '0');
});
registerEveryFrame(function() {
    if (farmers_position != farmer_posotion_next) {
        setObjTransform('farmer_armature', false, 'position', [farmers_position, '', ''], false);
        farmers_position = Math.round((farmers_position + move_steps) * 10) / 10;
    } else if (farmers_position == farmer_posotion_next) {
        farmer_position_prev = farmers_position;
    }
});

eventHTMLElem('keydown', ['BODY'], false, function(event) {
    if (farmers_position < 1 && getEventProperty('key', event) == 'a') {
        Move_Left();
    } else if (getEventProperty('key', event) == 'd' && farmers_position > -1) {
        Move_Right();
    }
    if (farmers_position < 1 && getEventProperty('key', event) == 'ArrowLeft') {
        Move_Left();
    } else if (getEventProperty('key', event) == 'ArrowRight' && farmers_position > -1) {
        Move_Right();
    }
});

eventHTMLElem('click', 'button_left', false, function(event) {
    if (farmers_position < 1) {
        Move_Left();
    }
});

eventHTMLElem('click', 'button_right', false, function(event) {
    if (farmers_position > -1) {
        Move_Right();
    }
});

registerEveryFrame(function() {
    for (let e = 1; e <= 9; e++) {
        empty_to_check = 'Empty.00' + String(e);
        emptys_distance[e] = getDistanceBetweenObjects('fruit_picker', empty_to_check);
    }
    for (let e = 10; e <= 99; e++) {
        empty_to_check = 'Empty.0' + String(e);
        emptys_distance[e] = getDistanceBetweenObjects('fruit_picker', empty_to_check);
    }
    for (let e = 100; e <= 384; e++) {
        empty_to_check = 'Empty.' + String(e);
        emptys_distance[e] = getDistanceBetweenObjects('fruit_picker', empty_to_check);
    }
});



} // end of PL.init function

PL.disposeListeners = function() {
    if (_pGlob) {
        _pGlob.eventListeners.forEach(({ target, type, listener, optionsOrUseCapture }) => {
            target.removeEventListener(type, listener, optionsOrUseCapture);
        });
        _pGlob.eventListeners.length = 0;
    }
}

PL.disposeHTMLElements = function() {
    if (_pGlob) {
        _pGlob.htmlElements.forEach(elem => {
            elem.remove();
        });
        _pGlob.htmlElements.clear();
    }
}

PL.disposeMaterialsCache = function() {
    if (_pGlob) {
        for (const mat of _pGlob.materialsCache.values()) {
            mat.dispose();
        }
        _pGlob.materialsCache.clear();
    }
}

PL.dispose = function() {
    PL.disposeListeners();
    PL.disposeHTMLElements();
    PL.disposeMaterialsCache();
    _pGlob = null;
    // backward compatibility
    if (v3d[Symbol.toStringTag] !== 'Module') {
        delete v3d.PL;
        delete v3d.puzzles;
    }
}



return PL;

}

export { createPL };
